### ISSUE TITLE
Custom money type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1094]
## Problem

We've decided to implement a custom Mathesar money type that is an alias to `NUMERIC` types. Currency will be specified through display options.

## Proposed solution

- Create a `Money` friendly type name in the service
- Create a `MATHESAR_TYPES.MONEY` type in the database that store currency amounts.  The amount should be a `NUMERIC` type.
- Users should be able to use the API to change a column to `MATHESAR_TYPES.MONEY` if it's possible to do so.
- Automatic type inference during file import suggests `MATHESAR_TYPES.MONEY` when it makes sense to do so.
- Existing `MATHESAR_TYPES.MONEY` should be renamed to `MATHESAR_TYPES.MULTICURRENCY_MONEY`

Please note that this issue does not cover display options; a separate issue will be created for those once https://github.com/centerofci/mathesar-wiki/pull/36 is finalized.

## Additional context

- See discussion on https://github.com/centerofci/mathesar-wiki/pull/36
- See [relevant meeting notes](https://wiki.mathesar.org/en/meeting-notes/2022-02#discouraging-money-type-and-directing-user-towards-number-type-with-currency-display-option)

**Comment by mathemancer** [comment]
@kgodey It turns out that the previous custom type was called `MATHESAR_TYPES.MATHESAR_MONEY`.  The reason for this is that it keeps the key `money` reserved for the default PostgreSQL `MONEY` type in a few auto-generated dictionaries.  So, I've kept this for the new custom money type:  It's called `MATHESAR_TYPES.MATHESAR_MONEY`.

**Comment by kgodey** [comment]
@mathemancer Sounds good.
