### ISSUE TITLE
Eliminate TypeScript types like `undefined | null`

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1113]
Types which contain unions like `undefined | null` are the sort of type I was trying to avoid by starting the discussion in #825. Indeed, now we have a [code standard](https://wiki.mathesar.org/en/engineering/architecture/front-end-standards#null-vs-undefined) to this effect.

However, #1080 introduced these problematic types in the following places:

- [TextArea.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/component-library/text-area/TextArea.svelte#L17-L17)
- [TextInput.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/component-library/text-input/TextInput.svelte#L8-L8)
- [CheckboxCell.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/components/cell/cell-types/CheckboxCell.svelte#L8-L8)
- [TextAreaCell.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/components/cell/cell-types/TextAreaCell.svelte#L6-L6)
- [TextBoxCell.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/components/cell/cell-types/TextBoxCell.svelte#L6-L6)
- [SteppedInputCell.svelte](https://github.com/centerofci/mathesar/blob/4101a0fde2220f2b4fe52c3ef7b381f748abefc8/mathesar_ui/src/components/cell/cell-types/common/SteppedInputCell.svelte#L8-L8)

Let's take `TextArea.svelte` as an example.

- Before we had:

    ```ts
    export let value = '';
    ```

    (Which types `value` simply as `string` by inference.)

- Now we have:

    ```ts
    export let value: string | undefined | null = '';
    ```

@pavish What's the rationale for this change? Can you convince me that we need `undefined`? Can you convince me that we need `undefined` **_and_** `null`?? If I'm convinced, then I'd like to see some code comments explaining why that code deviates from our standards.

I've put this in `[07] Initial Data Types` because this is review feedback to #1080 that I'd like to address before it begins to affect other code.

**Comment by pavish** [comment]
@seancolsen I'll try to explain with an example.

`TextBoxCell` is displayed on the sheet when the column is of a short text type. This component takes care of both displaying the content of the cell in select mode and then editing the cell by displaying a TextBox in edit mode.
1. The `value` accepts a `string`.
2. The `value` can accept `null` because we display the NULL component when it does.
3. The `value` can accept `undefined` because we need to create the component without having to pass the value. Eg., In the new row placeholder. If we make value `null`, it will display the NULL component and will send null as the value for the column to the server where it shouldn't send the column.

The `TextBoxCell` composes `TextBox` component. We could surely check the type and only pass a string to it, and handle value change by using the on input event. This will require an additional variable defined on TextBoxCell and an additional event handling, where it could be simplified with `bind:value`. The extra steps didn't seem worth it to me especially for a common component like `TextBox`, where we might have similar usecases in several parts of our code in the future.

The same logic applies for the other components which accept both null and undefined. 

I agree with the code standard we established, but that discussion relies on scenarios where the values are controlled only by the frontend. In this case `null` is a valid state of the backend whereas `undefined` is a state we need on the frontend. So we have to be able to accept both.

**Comment by seancolsen** [comment]
I see. Ok. I'm fine with this. Thanks for explaining @pavish 

I do think it would be nice to have some code comments explaining why that code deviates from our standard. But I'm not going to push it.
