### ISSUE TITLE
Can we move the column type config UI to a modal?

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1140]
## Context

- This is the column header menu:

    ![Peek 2022-03-04 08-50](https://user-images.githubusercontent.com/42411/156775279-e47628b9-e6e4-4e74-9840-b316b4868de9.gif)

- In #1076, I added a `Menu` component. I'd like to use that component for the column header menu because it has some new features like "disabled" and separate icon/form-element. The `Menu` component has support for _almost_ everything we're doing within the column header menu. But the UI within column header menu that deals with the type configuration is a bit special and would be more work to incorporate into the `Menu` component.

## Request

I'd like to move the type configuration to a modal instead of keeping it within the column header menu.

### Spec

Here are the specs that I'm requesting modifications to follow:

- The contents of the column header menu appear as:

    ![image](https://user-images.githubusercontent.com/42411/156797554-c1807df1-233b-42cb-99e6-56d56fe14c74.png)

- Clicking on "Configure Data Type..." opens a modal and closes the column header menu. The modal contains the type configuration form with "Cancel" and "Save" buttons.

### Shortcomings

- The above spec makes it a little harder for the user to see the current type of the column.

    I'd like to address this by showing a popover/tooltip on the type icon within the column header, like AirTable does:

    ![Peek 2022-03-04 11-11](https://user-images.githubusercontent.com/42411/156798822-d85c7df7-52ad-4e47-a6a9-f8ca0dd61c75.gif)
    
    I think we could address this separately from the changes to the column header menu.

- Navigating from the type configuration back to the column header menu takes one extra click (because you need to re-open the menu). Though in some cases that behavior may be preferable.

## Rationale

- Our UI of putting a form inside a menu is somewhat unconventional.
- Our code to implement it is really pretty messy. It would be way cleaner and easier to maintain if we separate the type config into a modal.
- As we continue to flesh out the type configuration (e.g. by adding default values), it might feel more squeezed to keep all that UI within such a small area.
- Moving the type config to a modal is the shortest path towards implementing the `Menu` component for the column header menu, which I'd like to do so that we can take advantage of its additional features and simplified code.

**Comment by seancolsen** [comment]
For reference during implementation, here's the code I used to generate the mockup above:

<details>
<summary>Code:</summary>

```svelte
  <Menu>
    <MenuHeading>Data Type</MenuHeading>
    <MenuItem icon={{ data: faWrench }}>Configure Data Type...</MenuItem>
    <MenuItem icon={{ data: faBan }}>
      <Checkbox slot="control" checked />
      Allow <Null />
    </MenuItem>
    <MenuItem icon={{ data: faClone }}>
      <Checkbox slot="control" checked />
      Allow Duplicates
    </MenuItem>

    <MenuDivider />
    <MenuHeading>Display</MenuHeading>

    <MenuItem icon={{ data: faSortAmountDownAlt }}>
      <Checkbox slot="control" />
      Sort Ascending
    </MenuItem>
    <MenuItem icon={{ data: faSortAmountDown }}>
      <Checkbox slot="control" />
      Sort Ascending
    </MenuItem>
    <MenuItem icon={{ data: faThList }}>
      <Checkbox slot="control" />
      Group by column
    </MenuItem>

    <MenuDivider />
    <MenuHeading>Operations</MenuHeading>

    <MenuItem icon={{ data: faICursor }}>Rename column...</MenuItem>
    <MenuItem icon={{ data: faTrashAlt }}>Delete column...</MenuItem>
  </Menu>
```

</details>

**Comment by kgodey** [comment]
Some questions before I form an opinion.

> The above spec makes it a little harder for the user to see the current type of the column.

I assume we can keep the "Data Type: <blah>" in the menu and still use a modal to configure/change the data type? This would additionally address this shortcoming.

Other questions:
- One concern is that if we need to show errors or confirmations within the modal, I'd like to avoid a double-modal pattern. Do you see this as a potential issue?
- I think the best pattern for this in the long run might be a side panel on the right rather than a modal, sort of like an "inspector" in other tools. I assume this would take more work to implement right now, though?

**Comment by seancolsen** [comment]
@kgodey 

> I assume we can keep the "Data Type: " in the menu and still use a modal to configure/change the data type?

First, just so we're clear on my proposal: The column header menu for all column types would look exactly as in the mockup above. If the column type is "Number", the menu will not have the text "Number" anywhere.

I'm not confident I understand what you're proposing. Are you proposing that we use text like "Number" (i.e. the name of the column type) as the label for the menu item that opens the type configuration modal? (This would be similar to the current UI.) If so, okay... we _could_. But I don't really like that. I've been looking a lot of different menu systems in researching this UI and I haven't seen one that works like that. If the menu item _has a form control_, **then** its label will describe a currently-set value. For example:

![image](https://user-images.githubusercontent.com/42411/156806322-de2314fe-e7e2-47fc-9930-4545b30fe44b.png)

But if the menu item _does not_ have a form control, then its label will describe the _action_ that the user will perform when clicking the menu item. For example, consider a menu item labelled "Email..." (for the Mathesar type "Email"). What _action_ will that menu item perform? Will it allow me to _email_ all the values in the column to somebody?

Our current UI skirts around this problem somewhat by placing a suggestive gear icon and arrow on the right side of the menu item. Those additional UI elements help to communicate that _something is a bit different_ about this menu item. But it's a non-standard pattern. We could use the column type name along with the gear icon and arrow (as we currently do). I'd be okay with that, if that's what it takes for us to agree on moving to a modal. In looking at menus like this in many different products though, I've observed a striking amount of consistency in the UX patterns, and I havn't seen a pattern like that anywhere. I think these UX patterns are well-established enough that it's worth it for us to follow them.


> I'd like to avoid a double-modal pattern.

I've considered this too, and I don't forsee any double modals here.



> side panel on the right rather than a modal, sort of like an "inspector"

It might be easy to build this. The hard part is the design and the specific and subtle UX decisions. For now I don't think we need that. But we can explore it later on if we do.

**Comment by kgodey** [comment]
@seancolsen I was picturing something like this:
![New Wireframe 1](https://user-images.githubusercontent.com/287034/156816056-3934bb21-e1cc-4579-b867-5653938375dd.png)

**Comment by seancolsen** [comment]
> I was picturing something like this:

Yeah I played with that exact thing too as I was working on this. That's super easy to implement, so yeah we could definitely do it. What's a little awkward is that our current styling for the menu heading (in following the precedent set by the current column header menu) makes the heading text smaller than normal. So it looks a little off. But I think that with some styling adjustments it might work great. It might mean bringing the size of the heading up to the default size. But that stuff is easy to tweak.

**Comment by kgodey** [comment]
I'll wait for @ghislaineguerin and @pavish to weigh in before my final opinion but I don't see any problems with following this approach temporarily. 

I do think we should strongly consider a sidebar inspector pattern in the upcoming UI styling milestone, for one, it will allow users to see the changes in their data as they are making them (rather than being obscured by a modal).

**Comment by ghislaineguerin** [comment]
@seancolsen I think the modal makes sense. We had initially considered that, but there were some concerns regarding hiding the table contents behind it. Sidebar inspector seems like a better solution (better table visibility), but since we are already using modals I think it's better to stick with that, otherwise we'll have to make additional decisions over what goes on sidebar vs modal.

**Comment by pavish** [comment]
@seancolsen I don't think a modal should be used here. I personally hate modals so I'm a little biased, but in this particular scenario I believe the current design offers a better experience than using a modal. I do not think we should ever compromise on the UX for DX.

If this is all about the `Menu` design, I remember mentioning that I purposely wanted `Dropdown` and `Menu` to be separate components for this exact usecase. I also mentioned it as a comment on the Menu component issue.

See https://github.com/centerofci/mathesar/issues/742#issuecomment-971476886

So, our code would look something like this:
```
<Dropdown>
  {#if view === 'default'}
    <Menu>
       <MenuItem on:click={changeType}> ... </MenuItem>
    </Menu>
  {:else if view === 'typeOptions'}
     <TypeOptions/>
  {/if
</Dropdown>
```

I think this is much better and saves more development time than switching to a modal, if that's your primary concern of raising this issue.


Replies towards your Rationale:

> Our UI of putting a form inside a menu is somewhat unconventional.

Tools like Airtable, NocoDB and many tools that are similar to us do this. Note: It's not a menu, it's a dropdown. Only the default options view is a menu.

> Our code to implement it is really pretty messy. It would be way cleaner and easier to maintain if we separate the type config into a modal.

Like I mentioned, the priority should always be UX first, and then DX. Also, I personally do not think changing to a modal would bring much difference, since type related configuration is already a component of it's own.

> As we continue to flesh out the type configuration (e.g. by adding default values), it might feel more squeezed to keep all that UI within such a small area.

Agreed. In this particular case, we need to think of the UX for advanced and rare operations. We should do this when we get there.

> Moving the type config to a modal is the shortest path towards implementing the Menu component for the column header menu, which I'd like to do so that we can take advantage of its additional features and simplified code.

Like I mentioned above, no it isn't. The column header is a dropdown and only the first view is supposed to be a Menu.

**Comment by kgodey** [comment]
@seancolsen I'll leave it to you and @pavish to figure out a solution here, since I don't have enough information to speak to frontend architecture. My general opinions are:

- Let's do what we need to do to unblock current work.
- I don't think a modal is the best pattern in the long run for configuring a column because it makes sense for the table to be visible while you're applying configurations.
    - I'd like to consider using the sidebar for this and other configurations (e.g. constraints) in the UI Styling milestone.
    - If moving it to a modal now is low effort and helps you move forward, I'm fine with it being a temporary solution. Otherwise, I think it might make sense to wait until the UI Styling milestone to avoid spending time on work we'll probably undo anyway.

**Comment by ForchaGlen** [comment]
Please may I work on this issue ?

**Comment by seancolsen** [comment]
@ForchaGlen No, we don't have a consensus on the path forward here, which is why the issue is still labeled with `status: draft`. Pavish and I need to chat more to resolve our disagreement. If we side with Pavish, then we'll be closing this ticket without any further work.

**Comment by ForchaGlen** [comment]
@seancolsen  okay , thank you.

**Comment by kgodey** [comment]
@ForchaGlen Please look at our [issues labeled `good first issue`](https://github.com/centerofci/mathesar/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee). Those are suitable for people to contribute to, please comment on one of those.

**Comment by Forchapeatl** [comment]
@kgodey thank you

**Comment by seancolsen** [comment]
@pavish and I still disagree on this, but for the sake of moving forward, I'm closing this ticket. We will just avoid implementing the DropdownMenu within the column header menu any time soon.
