### ISSUE TITLE
A new column not visible after a table rename

### ISSUE THREAD

**Issue by A1O** [centerofci/mathesar#1181]
## Description

A new column not visible after a table rename. The column only appears after the page has reloaded.
## Expected behavior

The new column should be visible without page reload.

## To Reproduce

1. Rename a table
2. Add a new column "Col1"
3. The new column "Col1" is not visible
4. Hit F5 (page reload)
5. The "Col1" is visible.

## Environment
 - OS: Ubuntu 
 - Browser:  chromium, firefox
 
This issue could be related to  #982.

## Additional context

![Peek 2022-03-16 10-50](https://user-images.githubusercontent.com/6394268/158554451-33cc74b2-5d75-4bcc-9c6c-8db66e7ea391.gif)

**Comment by seancolsen** [comment]
Thanks for reporting this and providing such an excellent description @A1O!

**Comment by tsun812** [comment]
Hello, I am interested in solving this issue and to get familiar with the codebase. I have about 20 hours/week for commitment. Please let me know if I can get started. Thanks!

**Comment by tsun812** [comment]
Hi guys, I was trying to create two columns after table rename without manual window refresh, it seems columns store is updated properly, however it doesn't re-render the UI.

I am thinking dispatch a custom event after table name, and trigger refresh() in tabularData.ts similar to column rename. if i do the refresh approach, what other data should I fetch?currently refresh button doesn't do the same as window refresh.

not sure if I am on the right direction..

**Comment by pavish** [comment]
@tsun812 Part of fixing this issue is to identify _why_ the UI doesn't re-render when the store values are updated. Once the reason is identified, we can decide on the approaches to fix the bug.

**Comment by tsun812** [comment]
Hi, It seems the Header.svelte(where column header display is) is subscribing to the columnsDataStore, am I missing anything?

**Comment by pavish** [comment]
@tsun812 Yes, it is. The code appears good but there is a race condition somewhere which is causing this bug. We need to identify that race condition and fix it. This issue is tricky and requires a better knowledge of the code base. 

If you'd like a better first issue, please look for issues tagged 'good first issue'. If you'd like to continue with this issue, I'd suggest trying to figure out the effects of table rename on all the table data stores. My hunch is that there is a different instance of column store created but the view is bound to the older one.

**Comment by tsun812** [comment]
Ok, thank you very much!!

**Comment by kgodey** [comment]
@tsun812 I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.
