### ISSUE TITLE
Add support to preview display options when importing data

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1208]
## Problem
We show a preview of a table along with a few records when the suggested changes inferred from the import data are applied to a table. As of now, only `types` changes can be previewed, but #1207 infers the data for suggesting `display options` as part of the `type_suggestion` endpoint. So we should add support for previewing `display options` too.

## Proposed solution
`tables/previews/` should accept  `display options` as part of the columns object that is sent and return the correct preview of the display options

## Additional Context
- Blocked by design work #1227

**Comment by mathemancer** [comment]
Regardless of my concerns in [this comment](https://github.com/centerofci/mathesar/issues/1207#issuecomment-1075838987) about previewing with _inferred_ display options, I think it would actually be a really good idea to let users preview imported data with their chosen display options (with some warnings when applicable). This might improve their ability to quickly assess whether the data was imported correctly.

One place where a warning might be applicable: A German might want dots for grouping separator, and `http://10.123.124.125` is both a valid IP address, and valid `MATHESAR_MONEY`. If we display it with the display style 'currency symbol first', 'period group separator', then they'd have to notice the type being incorrect rather than just seeing the garbled output (assuming we inferred it to be money, but it should actually be a URI).

**Comment by kgodey** [comment]
This should first be a design issue before it goes to the backend.
