### ISSUE TITLE
Blank row cells were added before user click add new row

### ISSUE THREAD

**Issue by tsun812** [centerofci/mathesar#1234]
## Description

Blank cells were pre-filled next to add new record button before user click on them. It doesn't match the pattern for adding new columns, and a bit confusing as blank cells should appear after user click add new icon.
## Expected behavior

Blank row cells will be added after user click add new row.
## To Reproduce

![mathesar_record_add_before](https://user-images.githubusercontent.com/52032119/160223205-de9f2ca2-fbf3-4a15-bf28-2d0dfd412a53.gif)

## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

**Comment by tsun812** [comment]
pull request that fix this issue: https://github.com/centerofci/mathesar/pull/1235

**Comment by kgodey** [comment]
@tsun812 This is an intentional design choice. We'd like users to be able to add a new record easily by adding data directly in the blank row. 

> It doesn't match the pattern for adding new columns

In a database, adding new records and adding new columns are very different operations. Adding a new column alters the _structure_ of the data (it is a [DDL operation](https://wiki.mathesar.org/en/engineering/specs/ddl)) so it should be harder to do than adding new data (which is a [DML operation](https://wiki.mathesar.org/en/engineering/specs/dml)).

I'm going to close this issue.
