### ISSUE TITLE
500s when patching column to a different type

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1276]
## Description
When patching a column to a different type, having `display_options` or `type_options` in the request results in a 500 if the new type does not allow them.

### Scenario 1:
* Create a text column
* Patch the column to URI type with `null` values for display and type options:
   ```
  {
    "type": "MATHESAR_TYPES.URI",
    "display_options": null,
    "type_options": null
  }
   ```
* Notice the following response with status code 500:
  ```
  [
    {
        "code": 4999,
        "message": "'NoneType' object is not iterable",
        "field": null,
        "detail": null
    }
  ]
  ```

### Scenario 2:
* Create a text column
* Patch the column to URI type with an empty object: `{}` for display and type:
   ```
  {
    "type": "MATHESAR_TYPES.URI",
    "display_options": {},
    "type_options": {}
  }
   ```
* Notice the following response with status code 500:
  ```
  [
    {
        "code": 4999,
        "message": "Cannot find a matching serializer for the specified type uri",
        "field": null,
        "detail": null
    }
  ]
  ```

## Expected behavior
* The response should not result in 500 for both scenarios.
* For Scenario 1, the request should succeed.
* For Scenario 2, the it would be easier for the client if the request succeeds. If that's against backend convention, the response should result in a 400.

**Comment by kgodey** [comment]
> For Scenario 2, the it would be easier for the client if the request succeeds. If that's against backend convention, the response should result in a 400.

If `display_options` is set to an empty object, we should remove all display options.

**Comment by Anish9901** [comment]
Can I work on this?

**Comment by silentninja** [comment]
@Anish9901 I have assigned the issue to you. This issue blocks a lot of frontend work, so a core contributor might take it if it takes too long to be completed(more than 2-3 days)

**Comment by silentninja** [comment]
Thanks! @Anish9901

**Comment by kgodey** [comment]
@silentninja I think if the frontend sends a request to remove all display options, the backend should treat it as a request to reset the display options to their default state (i.e. the user is removing all customizations). We should not let the display options end up in a unusable state.

Alternatively, you can validate required display options, but the first option seems more flexible.

**Comment by pavish** [comment]
@silentninja  Here are my thoughts:

1. I think the default state should be `None`. Like you mentioned, an empty object is set by the client, for which currently we do not have any validation. But we might possibly have it in the future.
2. `display_options` and `type_options` are properties of the Column, so I think we should allow setting values for them for all columns, even though they depend on the column type and some types may not have them. We can throw errors for invalid entries, but we should allow `null` and `{}` for all.

**Comment by kgodey** [comment]
Sounds good to me.

**Comment by pavish** [comment]
@silentninja  FYI, patch requests to the same type also seem to be failing with similar errors. I assume the fix for this issue would apply to that scenario as well.

**Comment by vrutik2809** [comment]
After a lot of debug on resolving [this](https://github.com/centerofci/mathesar/issues/1276) issue, i come to know that actual bug was on `SimpleColumnSerailizer`. This serializer is calling [DisplayOptionsMappingSerializer](https://github.com/centerofci/mathesar/blob/246ad98c4c714190c7a075e2a10b06a1d966ff0e/mathesar/api/serializers/shared_serializers.py#L127) which is extending [ReadWritePolymorphicSerializerMappingMixin](https://github.com/centerofci/mathesar/blob/246ad98c4c714190c7a075e2a10b06a1d966ff0e/mathesar/api/serializers/shared_serializers.py#L54). `ReadWritePolymorphicSerializerMappingMixin` is trying to get `email` key from `serializers_mapping` dictionary defined in  `DisplayOptionsMappingSerializer` which is currently not present there.
So temporary i have added `(MathesarTypeIdentifier.EMAIL.value: EmailDisplayOptionSerializer),` entry in `serializers_mapping` dictionary to check whether i am going in write direction or not and it is working.

Defination of `EmailDisplayOptionSerializer`:

```python
class EmailDisplayOptionSerializer(MathesarErrorMessageMixin, OverrideRootPartialMixin, serializers.Serializer):
    format = serializers.CharField(max_length=255, required=False)
```

**Comment by vrutik2809** [comment]
And in addition to this, we need to define a display option serializer for each Mathesar data type which includes DisplayOptionsMappingSerializer so that in future this type of error could not occur. As currently, I am trying to change the data type of column from email to text then it is showing me the same error. Again the reason is the same: no entry for text type

**Comment by silentninja** [comment]
> And in addition to this, we need to define a display option serializer for each Mathesar data type which includes `DisplayOptionsMappingSerializer` so that in future this type of error could not occur. As currently, I am trying to change the data type of column from `email` to `text` then it is showing me the same error. Again the reason is the same: no entry for `text` type

@vrutik2809 The source of error is correct, but instead of having a serializer for all the types, it would be better to have a default serializer that would ignore any display options for types that don't accept any display options

**Comment by vrutik2809** [comment]
Can we do like if `display_options` is null then irrespective whether matching serializer is there or not just return else if `display_options` is not null and if matching serializer for that type is not found then only raise Exception? We can also add a prior check for `display_options` whether the respective type has a facility for that or not.

**Comment by Anish9901** [comment]
@pavish @silentninja Since this issue is now closed can we uncomment `test_set_column_default_value`?
https://github.com/centerofci/mathesar/blob/e33b5eed35882645f0344959fcc3f7e6c77662b6/mathesar/tests/integration/test_columns.py#L60-L79

**Comment by silentninja** [comment]
@Anish9901 Thanks for pointing it out. Can you send a PR to uncomment it out

**Comment by Anish9901** [comment]
> Can you send a PR to uncomment it out

@silentninja Sure working on it.
