### ISSUE TITLE
Customize the filtering functions for FK columns

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1523]
## Current behavior

- Filtering on an FK column presents the user with different filtering functions that don't quite make sense given our UX with the record selector. For FK columns, the value within the filter condition will be acquired through the (modal) Record Selector and afterwards displayed within the input using the Record Summary for the acquired record. The numerical primary key value used for the filtering condition won't be displayed to the user unless it happens to be contained within the Record Summary. Thus, for example, selecting all Publications with and author _greater than_ "Octavia Butler" doesn't quite make sense -- in the quantitative sense, at least 😜.

## Desired behavior

- Filtering functions for FK columns look more like the functions for boolean columns. We should only have "is empty" and "is equal to".

**Comment by seancolsen** [comment]
@pavish since you're more familiar with the filtering than me, would you be able to offer any tips/answers on the best implementation strategy here?

**Comment by pavish** [comment]
@LFLATH I wouldn't want to create a new type for FKs, because the columns themselves have associated data types which we need to preserve.

We should be checking if the column is a PK or an FK while choosing the filters. An approach already in place for our Cell component can be found in `getCellCap` and `getDbTypeBasedInputCap` functions within `cell-fabric/utils.ts`.

The change should not be done in `filtering.ts` since it's essentially a mapping of each type to it's associated filters and it should not have to worry about the column's attributes such as whether it's a PK or a FK. 

We would need to create a similar util like the Cell component's util file, to determine the filters before they are passed to a `ProcessedColumn` in  the`processColumn` function within `table-data/processedColumns.ts`.

**Comment by LFLATH** [comment]
Thank you!! That’s very helpful. I will start looking at that in a minute. Thanks for the rapid replies.

**Comment by LFLATH** [comment]
Hello! I have a "working" solution for this problem, but I think that it is very inelegant. I am attaching two images of what the behavior currently looks like on my end. If this is what is envisioned, I can submit a PR, for review. Sorry for all the messages!!

<img width="629" alt="Screenshot 2022-11-21 at 8 42 06 PM" src="https://user-images.githubusercontent.com/63031670/203196338-346bd71d-a18a-41f7-a421-fbf2a7b9720a.png">
<img width="889" alt="Screenshot 2022-11-21 at 8 41 07 PM" src="https://user-images.githubusercontent.com/63031670/203196337-2d171ce4-c532-4970-a10a-142388717419.png">

**Comment by pavish** [comment]
@LFLATH The behavior from your screenshots is what we expect. Please raise a PR so that we can take a look at the code. Thanks!
