### ISSUE TITLE
Hide grouping separators in display of numbers within primary key cells

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1527]
## Current behavior

- Primary key columns typically have a Number type. We default to formatting all numbers with grouping separators, e.g. `1,234`. Within the PK cells, the grouping separators look a bit weird, especially since we decided to left-align these values in #1525.

    ![image](https://user-images.githubusercontent.com/42411/184627709-1c3fba20-9173-47b4-ac57-9a85da0caaa2.png)

## Desired behavior

- Primary key columns should get formatted without any grouping separators, e.g. `1234`.

**Comment by kgodey** [comment]
@seancolsen in https://github.com/centerofci/mathesar/issues/1329, there is a UX section that describes grouping separators like so:

> Add a new form field labeled "Use Grouping Separators", with a dropdown input having options "Yes", "No", and "Auto". Display this new field before the already-existing "Format" field.
> 
> For integers, the default is "No".
> 
> For non-integers, and Money, the default is "Yes".

I like this UX with integers having a different default for grouping separators. It will fix this issue (and will also work better for non-PK values like years). Although #1329 is closed, this does not actually appear to be the current behavior in the product. Was it not actually implemented or was there a regression?

Regardless, I think we should implement that behavior instead of special handling for FKs and PKs.

**Comment by seancolsen** [comment]
After chatting with Brent about this today, I'm closing in favor of #1709, which lays out a better approach.
