### ISSUE TITLE
Date picker is showing 1 week as 6 days

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1579]
## Description

Our date picker is showing weeks as 6 days instead of 7. 

## Expected behavior

Weeks should be 7 days and each number should be aligned underneath the correct day.

## To Reproduce

Edit any date field, for example the [Team Event Schedule](https://staging.mathesar.org/mathesar_tables/3/15/) on staging.

## Environment
I found this on staging.

## Additional context

<img width="330" alt="Screen Shot 2022-08-29 at 5 32 11 PM" src="https://user-images.githubusercontent.com/287034/187303455-d4d99b81-3b34-45d9-80ed-dd667b37e3b2.png">

**Comment by seancolsen** [comment]
@pavish because you [said](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$5-c0PG_NkQ0zyJPwY3C8N6jqbHp9jPJkkgLnNZFYcLs?via=matrix.mathesar.org&via=matrix.org) _"It's a single line fix"_, it seems like you already know what needs to be done, so I'm assigning this to you just avoid someone else getting deep into troubleshooting it unnecessarily.
