### ISSUE TITLE
Provide targeted error messages when tables & columns involved in an exploration are no longer present

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1596]
* Create a new exploration with a base_table and some initial columns
* Delete some of the columns in the table directly
  - Notice that the API responds with a 500 error code
* Delete the table which is the base_table of the query
  - The query also gets deleted
  - We need to show these in the warning message while prompting for user confirmation
* Delete a linked table whose columns we use as initial_columns in the query
  - The API responds with a 500

Expected:
* The frontend needs to show the columns and highlight the ones that are no longer present
* The API response needs to provide both the column structure and targetted errors

**Comment by mathemancer** [comment]
@pavish What do you mean by "column structure"?

**Comment by pavish** [comment]
@mathemancer It refers to the response for "columns" endpoint (the 'columns' property in the RPC style endpoint). It should contain all the output columns, including the invalid ones. The frontend will highlight the invalid columns using the error information, and would allow the user to delete them from the query.

**Comment by mathemancer** [comment]
Ah. At that point, we will only be able to recover the column alias (and the ID that didn't work, but that isn't too useful for the UI), and where the column was in the output order. No type info or display options would be available at the point where the column is missing from underneath the query.

**Comment by pavish** [comment]
That should totally be fine. I'd also need the column display_name. The idea is to display the column with an error indication on the entire column(a red background maybe), and a helpful error message to the user. So, I'd only need the display_name, alias, and output order of the column.

**Comment by mathemancer** [comment]
I forgot about `display_name`. That's no problem, as it's stored along with the alias in the UIQuery.

**Comment by silentninja** [comment]
> Delete the table which is the base_table of the query
> The query also gets deleted
> We need to show these in the warning message while prompting for user confirmation

The warning should be part of the dependency UI related to #398, based on the [discussion we had before(Milestone 3)](https://hackmd.io/@mathesar/SyKV9X_h9?type=view#Priorities-for-the-GSoC-project) it something we have planned for future(post-release improvement milestone maybe). Is there any reason we need it now?


> Delete some of the columns in the table directly
> Delete a linked table whose columns we use as initial_columns in the query
> Notice that the API responds with a 500 error code

There will be a 500 error when an API uses a Query object whose columns have been deleted, we should be deleting the UIQuery or taking appropriate action when the underlying objects are deleted rather than letting the stale `Query` stay in the database. This would help us throw a `404` error right when the Query is used instead of complicating things.


@pavish The error is thrown right when the column structure is being constructed, so I would have to bypass the exceptions and handle it separately which would lead to a lot of alternate pipelining. So my question would be is it worth the effort trying to show the columns that were deleted along with all the columns or is there a simpler solution that you would settle for?

**Comment by dmos62** [comment]
I guess the reason we want this for the live demo is so that frontend can handle queries with bad initial columns. I agree that the dependency API is the longterm solution. Not sure what the shortterm solution is. We probably either **a)** check that the django columns representing the referenced columns exist each time we run a query, or **b)** we return an additional field `columns-present` when `GET`ing a query. If performance hit is neglibile, **a)** is probably preferable.

**Comment by pavish** [comment]
@silentninja 

> The warning should be part of the dependency UI related to https://github.com/centerofci/mathesar/issues/398, based on the [discussion we had before(Milestone 3)](https://hackmd.io/@mathesar/SyKV9X_h9?type=view#Priorities-for-the-GSoC-project) it something we have planned for future(post-release improvement milestone maybe). Is there any reason we need it now?

We need to atleast show a message on the frontend regarding this even if we don't exactly show which queries are deleted. We can place it for later.

> There will be a 500 error when an API uses a Query object whose columns have been deleted, we should be deleting the UIQuery or taking appropriate action when the underlying objects are deleted rather than letting the stale Query stay in the database. This would help us throw a 404 error right when the Query is used instead of complicating things.

I don't think we should delete the Query object if a column is deleted. This would be extremely confusing for the user and a terrible UX, so a 404 is out of the question. If we show any error without a way for the user to rectify them, the user will never be able to recover the query, or understand why it's broken. This may lead them to think that the entire feature is broken.

> The error is thrown right when the column structure is being constructed, so I would have to bypass the exceptions and handle it separately which would lead to a lot of alternate pipelining. So my question would be is it worth the effort trying to show the columns that were deleted along with all the columns or is there a simpler solution that you would settle for?

How much work would this be/how long would it take? I would expect a 400 with the entire query object returned from the server and the list of columns that are not present, so that the user can recover the query or atleast understand the issue. I do think it's worth the effort. I don't see a simpler solution for this problem.

**Comment by silentninja** [comment]
> I don't think we should delete the Query object if a column is deleted.

I was suggesting that we should be having the user take an action about the `Query` object that still references the `Column`

**Comment by silentninja** [comment]
The possible scenarios for these errors and their solution are:
- The `base_table` is deleted
    - Using Mathesar - Call `/tables/<id>/ui_dependents/` API, ask the user to take action regarding the query.
    - Directly from the database - The `Query` object is deleted due to an invalid foreign key reference. Not something we can provide a reasonable fix for right now.
- The `initial_columns` is deleted 
  - Throw an error when the user tries to run the query using the `/run/` API with the necessary details for the user to fix the problem(doesn't matter how it is deleted).

 - The table of the column in the join path is deleted - This leads to the deletion of the column in the join path and is the same as the next scenario `The column in the join path is deleted`
 - The column in the join path is deleted - In this case we don't have access to the column name. So the user has to manually make the change based on the column id
