### ISSUE TITLE
Filters not applied when calculating count of items within group

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1599]
## Reproduce

1. Go to the Library Management schema.
1. Load the Table Page for the Publications table.
1. Group by "Publication Year".
1. Observe the first group, for year 1900, to contain 10 records and to display a "Count" of 10. Good.
1. Add a filter condition requiring Title to contain the string "To".
1. Observe the first group, for year 1900, to contain 2 records.
1. Expect "Count" to display 2.
1. Observe "Count" displays 10.

![image](https://user-images.githubusercontent.com/42411/188676046-46fe3997-5c5e-433c-9f5e-f0f73bf36bb8.png)

**Comment by mathemancer** [comment]
Interesting. I consider this to be the expected behavior. If I wanted to count the number of results after a filter, I'd use the Data Explorer. For me, filtering the records in this view isn't supposed to change calculated statistics like "count", it's supposed to let me find the row I'm interested in working with by reducing the number of results. 

From a more technical perspective, for ranged grouping, filtering before grouping (which is your apparent expectation) changes the parameters of the given groups. If I filter a numeric column to cut of its upper range (i.e., something like `WHERE mycol < 10`), then the bounds of the automatically generated groups would change accordingly. This would (I think) be kind of confusing.

OTOH, if one wants to count based on ranged grouping, one can't do that in the data explorer until we have the relevant features implemented...I don't think we should indulge in over-complicating the table records view based on that deficiency, though.

To some extent, I consider showing the count in this view _at all_ to be extraneous, and potentially confusing. I'm becoming less and less convinced that grouping makes sense in this view (as opposed to bringing any relevant functionality into the data explorer).

@ghislaineguerin @kgodey Any opinion here? Is the user supposed to be using the table view for querying (albeit with a reduced feature set), or for viewing/editing data? Or both?

If both, we may want to figure out how to handle these order of operations problems and their implications more clearly. I see from the UI (should have noticed earlier, sorry) that the implication is that we first filter, then sort, then group (going from left to right). But, the actual implementation goes group, then sort, then filter on the back end. The order of these operations changes the output.

**Comment by seancolsen** [comment]
Can we just remove `count`?

**Comment by pavish** [comment]
I'd like not to remove `count`, and the count reflecting the filtered results.

> I consider this to be the expected behavior. If I wanted to count the number of results after a filter, I'd use the Data Explorer. 

We do not show a grouped result to the user in the table page, what we show is an ordered set of rows sectioned by their groups. I think from the user perspective, it is important to reflect the filtered count in each of those sections.

> For me, filtering the records in this view isn't supposed to change calculated statistics like "count", it's supposed to let me find the row I'm interested in working with by reducing the number of results.

I would agree with this if we had an UX which has filters per group, and not a common filter. I'd expect the common filter to have a higher precedence over the groups.

**Comment by kgodey** [comment]
I agree that filters should take precedence over grouping. It is confusing to see a group count that doesn't match the data you see in front of you.

> Is the user supposed to be using the table view for querying (albeit with a reduced feature set), or for viewing/editing data? Or both?

Both. 

> we may want to figure out how to handle these order of operations problems and their implications more clearly.

I agree we should have a defined order of operations, here's my response to the [email thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/mhuc2cWLPXM/m/Om-jcOxgBwAJ).

---

I don't think we should spend any time or energy focusing on rethinking existing features (like whether grouping makes sense where it is) until we have released our first alpha release.
