### ISSUE TITLE
Can we remove the "Close" button on Explorations?

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1601]
_This ticket is a design question/discussion. We can close it when the discussion is resolved, opening other tickets as-necessary to track any work to be done._

- I find this close button weird.

    ![image](https://user-images.githubusercontent.com/42411/188696778-bca5469e-4b0e-4068-ac7c-03d6a43066bd.png)

    If I navigate directly to that page, what is the meaning of "close"? I didn't have anything open before. When I click it, Mathesar navigates to the Schema Page. But we already have navigation in place in the header for that purpose. Are there other things we expect this button to eventually do?

- Also if its purpose is navigation, then I would expect it to be a link instead of a button.

- I skimmed over the [design specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/visual-query-builder.md) and didn't see anything about the close button specifically.

- In #1591, @rajatvijay has modified the behavior of this button to behave more like a browser "back" button. Are his modifications in-line with other peoples' expectations for the behavior of this button? If "back" is our expected behavior, then why do we need a button at all when the user can use their browser's "back" button?

- Unless someone can present a compelling use-case for the "Close" button, I'd like to remove it.

@pavish @ghislaineguerin @kgodey @rajatvijay can you weigh in with your opinion? Can we remove the "Close" button?

**Comment by kgodey** [comment]
We do not have the Exploration Page yet. The close button should close the "edit" view of the Exploration and go back to the "read-only" view of the Exploration (i.e. the Exploration Page).

**Comment by seancolsen** [comment]
Ok so we'll have a page to _edit_ an exploration (implementation already started) and a page to _view_ the exploration output without editing (implementation forthcoming). _(As a side note, I think it would be wise to workshop the naming of these pages a bit, perhaps even abandoning the term "Exploration Page" altogether since the introduction of a view-only makes the terminology somewhat ambiguous.)_

Once we have the _view-only_ Exploration Page, then we need a way to navigate to it from the _edit_ page. That's reasonable. **So can we remove the "Close" button now because we don't have that page yet?**

And when we _do_ implement that _view-only_ page, I don't think the navigation to it it should be a _button_ labelled "Close". Rather, **I think the navigation should be a _link_ labelled "View Results" (or similar). Does that sound okay?**

**Comment by pavish** [comment]
@seancolsen 

The _view-only_ page i.e `Exploration Page`, would look similar to a normal table page. When a user clicks on an exploration from the schema page or the breadcrumb, they will be directed to this page. This page will contain an edit button, which will open up the Data Explorer in it's _edit_ mode (the edit mode is what we currently have implemented).

> I don't think the navigation to it it should be a button labelled "Close". Rather, I think the navigation should be a link labelled "View Results" (or similar)

I find "Close" to be more appropriate compared to "View Results", since the Data Explorer works like an editor here, which is meant to be opened only from the Explorations page. We will not have a direct url which opens it in the edit mode.

When the user opens the Data Explorer separately (from a link in the schema page or from the table inspector), it will not open in the _edit_ mode, it would open in _explore_ mode. In this scenario, the Data Explorer would work more like an exploration pane rather than an editor. We would have to make some UX changes to the header to better represent this. In the _explore_ mode, there will be no Close button. We could potentially remove the editable title and just mention "Data Explorer", and upon trying to save, we'd get the name from the user.

@kgodey @ghislaineguerin Does this sound okay?

> So can we remove the "Close" button now because we don't have that page yet

We'd have this page implemented for the live demo. Removing the button is a small change but I don't see any need to do this temporary change right now.

**Comment by seancolsen** [comment]
I'm confused. I have more questions, more concerns, and many more thoughts -- and I think it'll be much faster to resolve this conversation synchronously. 

I've added this as an agenda item for [tomorrow's meeting](https://hackmd.io/OEXWY519TceOUi53q0Ay1A).

**Comment by kgodey** [comment]
Talking about it at the meeting tomorrow is fine. This is all in the [Navigation spec](https://wiki.mathesar.org/en/design/specs/navigation) also.

> When the user opens the Data Explorer separately (from a link in the schema page or from the table inspector), it will not open in the _edit_ mode, it would open in _explore_ mode

I assume "edit mode" is "Open Exploration" in the navigation spec and "explore mode" is "New Exploration" in the navigation spec.

For some reason, Exploration Page is in the "Navigation structure diagram" part of the spec but not in the "Navigation via page url" section.

---

The Data Explorer (and pretty much all our other features, including navigation) will need quite a bit of polish before it's ready for the demo video. We'll handle that during the "demo video readiness" feature this cycle. We should hold off on any specific UI changes like the one in this discussion until "demo video readiness" is complete because it may not even be relevant by then.

**Comment by pavish** [comment]
> I assume "edit mode" is "Open Exploration" in the navigation spec and "explore mode" is "New Exploration" in the navigation spec.

Yes, that is what I intended. I would like to lose the term "New Exploration" though, since it gives the impression that explorations are always persistent, like creating a new file.

> We should hold off on any specific UI changes like the one in this discussion until "demo video readiness" is complete because it may not even be relevant by then.

Agreed.

**Comment by seancolsen** [comment]
We discussed this today and clarified that the design we're heading towards is as follows:

- We'll have three pages:
    - The **Data Explorer** page at `/<db_name>/<schema_id>/data-explorer`
    - The **Exploration Viewer** page at `/<db_name>/<schema_id>/exploration/<exploration_id>` (also simply called the **Exploration** page, though I'll be using "Exploration Viewer" here to be more explicitly clear.) This page is not yet implemented.
    - The **Exploration Editor** at `/<db_name>/<schema_id>/exploration/<exploration_id>/edit`

- From the Schema Page, clicking on an exploration will direct the user to the **Exploration Viewer** page.

- From the **Exploration Viewer** page, there will be an "Edit" link to navigate to the corresponding **Exploration Editor** page.

- From the **Exploration Editor** page, there will be an "View Results" (or similar) link to navigate to the corresponding **Exploration Viewer** page.

- The "Close" button, currently implemented on the **Data Explorer** page will be removed.

As such, I'm closing this ticket because our "design" work is complete. I assume @pavish will handle the necessary changes or create tickets for them as needed.

**Comment by ghislaineguerin** [comment]
I believe it is OK to remove it. The close button was included in the
prototype but not in the spec, so that might be why it was included. The
initial aim was to offer a mechanism to return to where Data Explorer was
launched, for example, if it was launched from the 'Record Page.'
It was also included since we had contemplated the idea of quitting Data
Explorer without saving, so an explicit "close action" was needed to leave,
instead of simply navigating back, which may trigger a warning for "unsaved
changes."
