### ISSUE TITLE
Update table inspector message for deleting records.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1679]
If there’s only one record selected, the delete record action should just say “Delete record”, not “Delete 1 record”.

**Comment by seancolsen** [comment]
I stumbled upon the code in question here while considering another issue today and, in thinking about an elegant way to fix this at a lower level, I ended up making some changes to the languageUtils code that I recently wrote. As such, I'm re-assigning this ticket to me. I trust that because this ticket is not yet placed in an iteration, @rajatvijay hasn't yet started work. Either way, this is very small, so I don't anticipate problems re-assigning it.
