### ISSUE TITLE
Unable to select column when table has no records

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1684]
* Create a table with no records and try selecting a column
* UI does not allow selecting the column, to modify it in table inspector

This is because our selection logic depends entirely on cells, and a table with no records has no cells. We need this for the ~~live demo, because we'd be allowing users to create a table from scratch~~ demo-video.

**Comment by kgodey** [comment]
We're creating tables from scratch in the demo video, this needs to be fixed sooner.

**Comment by rajatvijay** [comment]
@seancolsen @pavish I prefer having a new key in the selection store to store the column selected instead of changing the whole selection logic based on cells. 

Unfortunately that will lead to some if else blocks inside the selection store but that will not hamper the majority use cases where we can use cells as the lowest entity to define a selection. 

Let me know your thoughts before I move ahead on this

**Comment by seancolsen** [comment]
@rajatvijay that's what I had in-mind too.

**Comment by pavish** [comment]
@rajatvijay 
I'd prefer the selection store to utilize a different structure instead of just the identifier string array, something like:
```ts
{
   type: 'cell' | 'column' | 'row',
   identifiers: string[],
}
```

But if you find that this structure would take a lot more work, please create a draft issue for it which we take after our initial release, and we can move ahead with your suggestion for now.

**Comment by rajatvijay** [comment]
@pavish I have an argument against it but I created a new issue #1732 to discuss further since this requires some work and the bug is blocking a critical feature.
