### ISSUE TITLE
We should be able to create queries up to three relationships away

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1796]
Reported by @seancolsen 

---

I want to see checkouts and their associated authors like this:

```sql
select
  "Checkouts".id,
  "Authors"."Author First Name",
  "Authors"."Author Last Name"
from "Checkouts"
left join "Items" on "Items".id = "Checkouts"."Item"
left join "Publications" on "Publications".id = "Items"."Publication"
left join "Authors" on "Authors".id = "Publications"."Author"
```

If I set "Checkouts" as my base table, I can get to "Publications", but I can't navigate through the joinable tables tree deeply-enough to add information from "Authors".

![image](https://user-images.githubusercontent.com/42411/193664659-426a0f2f-20cf-44f2-b60d-d9c6da7632a9.png)

Similarly, I want to set Authors as my base table and see a list of all Items (not Publications) by that author.

**Comment by seancolsen** [comment]
@kgodey the title of this ticket doesn't quite reflect what I'd like. I want to be able to create queries up to _infinity_ relationships away. I don't see any reason why we shouldn't be able to do that. Imposing an arbitrary limitation on the depth seems unnecessary to me.

**Comment by dmos62** [comment]
@seancolsen our current setup is such that we fetch all the linked tables up to a certain depth. We limit it to a depth, because the search cost increases with the depth. @mathemancer will have more insight.

**Comment by seancolsen** [comment]
> we fetch all the linked tables up to a certain depth

Instead, can we fetch the linked tables when the user clicks to expand the nested items?

**Comment by seancolsen** [comment]
Or -- what I've proposed a number of times and still maintain would be a superior design -- we make the front end aware of the _entire_ schema structure (all tables, columns, constraints), entirely obviating the need for the `linked_tables` API altogether.

**Comment by pavish** [comment]
> Or -- what I've proposed a number of times and still maintain would be a superior design -- we make the front end aware of the entire schema structure (all tables, columns, constraints), entirely obviating the need for the linked_tables API altogether.

This would be a pain to maintain and impossible to work with in the long run when more than one person is working on the same Mathesar instance, without a websocket in place to keep upto date with changes. Doing this would mean replicating the entire db object metadata on the frontend. I do not think we should be putting our efforts here and we should try to defer as much as handling to the backend as possible. Also, the search cost @dmos62 mentioned would remain the same whether or not we do it on the backend or on the frontend.

> Instead, can we fetch the linked tables when the user clicks to expand the nested items?

This should be fine. But we need to discuss if this a priority for the live demo/initial release. I would prefer focusing more on the table page and basic operations and deferring this to later.

**Comment by dmos62** [comment]
I can see three solutions:

1. increase depth limit (possibly causing performance problems);
2. do something more iterative, where we prefetch a few depths-worth of links, and user-selected links are followed deeper on demand (seems fiddly in my head);
3. find a cheaper way to return links (presuming that's possible).

> we make the front end aware of the entire schema structure (all tables, columns, constraints), obviating the need for the linked_tables API altogether

@seancolsen Both frontend and backend need to know what is linked to what and how. Would it be ok to duplicate that logic between them?

Also, isn't frontend already aware of everything about user schemas?

**Comment by kgodey** [comment]
While making queries up to infinity relationships away is a noble goal, I think it's out of scope for the live demo. The product spec explicitly specifies that it should work up to three relationships away, and this was for a bunch of reasons – performance, relationship loops, usability, etc. None of these are impossible problems to solve, but the cost/benefit ratio makes solving those problems a bad use of our time right now.

**Comment by dmos62** [comment]
So, @seancolsen @kgodey, would increasing the depth limit to 3 foreign links solve this issue in the short term? Presuming it doesn't have a bad performance effect.

**Comment by seancolsen** [comment]
I don't think it's worth putting _any_ time into this issue for the live demo -- and apologies that I didn't notice the milestone on this ticket when I made my first comment here. (I mentioned lots of stuff in my Data Explorer critique that I didn't think would necessarily be relevant for the live demo.) But for the longer term, I would like us to find a solution that does not impose a limit on the depth. To me it seems straightforward to compute the table relationships each time the user expands an item. If that computation happens on the back end, then we make an API request to do it. If that computation happens on the front end, then then front end would require access to the entire schema data (controversial). In either case there should not be any performance concerns here because the depth is only `1`. That's what I like better about this design. It's simpler. There's no recursion aside from manually user-driven recursion. But to reiterate -- I don't think we should get into this _at all_ until after the live demo -- and probably not even until after the first release.

**Comment by kgodey** [comment]
@seancolsen I'm in full agreement with you, including the part where we don't investigate further until after the first release :)

For the live demo, we should make the depth limit 3, so this issue as originally specced is still relevant.

**Comment by mathemancer** [comment]
Regarding performance:

On the library data set, no depth that fits within the data set (no two tables are farther apart than depth 4) is a performance problem. Setting `max_depth=4` on the `Patrons` table returns in ~150ms on my machine.

On the other hand, the academics data set is specifically set up to stress test things like finding joinable tables. Starting from the `academics` table, I have:
- `max_depth=2`: ~1150ms
- `max_depth=3`: ~3500ms
- `max_depth=4`: ~10500ms
- `max_depth=5`: ~30000ms

I would consider this a performance problem. The difference is in the number and "richness" of foreign key link options that need to be explored when finding the joinable tables.

As for iteratively requesting more joinable tables as the user expands something, this would let us prune the search space to only the path the user is interested in, giving massive performance benefits in situations like the `academics` dataset.. The downside of this approach is that we wouldn't be able to prune obviously nonsensical links as easily (maybe not at all). If you follow the same link in both directions, you're just adding a copy of a given column to the query twice. The current algo prunes this out, since otherwise you confuse users trying to figure out which version of a column to add, when they're actually identical.

**Comment by kgodey** [comment]
Thanks for investigating, @mathemancer. I think we should do `max_depth=3` here and create separate issues for the performance implications as needed.

**Comment by seancolsen** [comment]
> separate issues for the performance implications as needed.

Before anyone spends time on improving performance of higher `max_depth` values, I would appreciate having the opportunity to continue making my case for delegating all the recursion to manually user-driven events, thereby constraining `max_depth` to `1` in all cases. I don't understand this comment...

> The downside of this approach is that we wouldn't be able to prune obviously nonsensical links as easily (maybe not at all). 

...but for priority's sake, I don't think now is the time to continue that conversation. I'm just saying: please keep in the loop when we circle back to this problem later.
