### ISSUE TITLE
Improve default display names of grouped & aggregated columns

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1812]
Update from pavish:

When summarizing a grouped table result:
`Count(id)` is a confusing name, we should name the column `<table name> count` when we're summarizing a primary key.

**Comment by pavish** [comment]
@dmos62 Since all display_names are now generated at the backend, I'm assigning this issue to both of us.

Expected initial display_names from backend:
For grouped columns: **<initial_column_display_name> group**
For aggregated columns:
 - Array aggregation: **<initial_column_display_name> list**
 - Count aggregation: **<initial_column_display_name> count**

As for summarizing a grouped table, the frontend decides the display name, which this issue is primarily about. It will send the count aggregation as **<table_name> count** as this ticket mentions.

@kgodey Let me know if this is inline with your expectations.

**Comment by kgodey** [comment]
Yes, that sounds fine.

**Comment by pavish** [comment]
I believe this has been fixed in one of the previous PRs.
