### ISSUE TITLE
Backup and restore data from Mathesar

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1815]
See [this email thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/qIE5gn399pE/m/ojAHZi-8BwAJ)

Tasks:
- [x] #2001 
- [x] #2002
- [ ] #2006

**Comment by dmos62** [comment]
Proposal we arrived at so far:

- CLI-only interface;
- database-level backups (schema-level harder to do, because of dependencies);
- dump user database with `pg_dump`;
- dump relevant Mathesar state (like queries and display options; see #2001) to a JSON structure;
- the JSON will mostly consist of regular serializations of our service layer structures, but it will also include a mapping from backup-instable to backup-stable identifiers (e.g. table oid or Django id to table name), and when restoring we'll use that to translate the rest of the JSON;
- investigate putting that JSON inside the SQL dump itself (maybe as a comment, depends on dump format);
- as last resort, archive the SQL dump and JSON as two separate files inside a single `tar` archive.

**Comment by kgodey** [comment]
@dmos62 how will restoring work? Will the entire database be over-written, or will we need to implement a UI for switching between databases?

**Comment by kgodey** [comment]
Okay, so for the new user database to be accessible in the UI, we'll need to do some design and frontend work for a mechanism to switch between databases. Please add that to the requirements, it shouldn't be much work.

**Comment by dmos62** [comment]
Edited the [first comment](https://github.com/centerofci/mathesar/issues/1815#issuecomment-1332464972).

**Comment by kgodey** [comment]
@seancolsen please note frontend work here, I saw that you'd marked frontend work for this feature as complete.

**Comment by dmos62** [comment]
We've decided to not do backup/restore for cycle 6.
