### ISSUE TITLE
Improve performance when fetching records using DBQuery

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1841]
## Problem

We are using DBQuery infrastructure to fetch records in the following API's
1. `/db/v0/queries/run/` 
2. `/tables/<id>/records/`

Both of these queries tend to be really slow especially when foreign key columns are involved.

Most of the queries issued to the Database are the metadata reflection related queries happening in `db.queries.base.DBQuery.initial_relation`

## Analysis

Taking a deeper look at the queries, it looks like the `db.tables.operations.select.reflect_table` used by `db.queries.base.DBQuery.initial_relation` is the cause of numerous reflection queries https://github.com/centerofci/mathesar/blob/bf2693ae020a6daa22b0afb188b19f39a8604fc5/db/queries/base.py#L114

I tried using a `cached metadata` and the function still ends up with duplicated reflection calls, I assume this is happening due to `extend_existing=True` used by the  https://github.com/centerofci/mathesar/blob/bf2693ae020a6daa22b0afb188b19f39a8604fc5/db/tables/operations/select.py#L19

## Proposed solution

We should consider setting `use_existing` when reflecting a `Table` or refactor the `db.queries.base.DBQuery.initial_relation` to fetch table names and columns directly from the database skipping SqlAlchemy objects.

**Comment by mathemancer** [comment]
Unfortunately, if we get rid of the SQLALchemy objects, we won't be able to (easily) select from the resulting `initial_relation` with our current infrastructure. I suggest modifying `db.tables.operations.select.reflect_tables_from_oids` to actually get the tables in bulk, using proper `metadata.reflect` calls (one per schema, arrgh). Then use that function instead of individual `reflect_table` calls in the `initial_relation` property.
