### ISSUE TITLE
Specify algorithm for deriving a default grouping transformation

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#1866]
We want the frontend to be able to incompletely specify a group-aggregation transformation, and for the backend to be able to provide sensible defaults for the rest of the transformation's specification. What is the algorithm for deriving this sensible, default group-aggregation transformation?

**Comment by mathemancer** [comment]
Assumption: The user has chosen a single column to summarize over. We need to choose a reasonable set of columns for the underlying `GROUP BY` clause.

If the chosen column is not unique-constrained (i.e., it's not a primary key, and it's not subject to a single-column unique constraint), return the set containing only the chosen column.

Otherwise, if the chosen column _is_ unique constrained, return the set containing
- All initial columns of the table containing the chosen column.
- All initial columns from tables linked to the table containing the chosen column only through forwards fkey relationships (this is determinable by observing `"multiple_results": False` in the response from the `joinable_tables` function).

The reason for this is that given a unique-constrained summarizing column, there exists a function (say, `f`) from that column to every column in the described set where the mapping is defined by the row relationship. (This is a little fuzzy. Here, we consider a "column" to be ordered by the row relationship, or by the join via the foreign key(s) (the join parameter path).)

The implication of that function's existence for each column is that any aggregation to a list of the values of such a column, grouped by any grouping set containing the summarizing column would result in a list of the same value over and over.

I hope this is clear enough.

**Comment by dmos62** [comment]
Is below correct?

```
group_by_columns = set([user_selected_col])
if (is_unique_constrained(user_selected_col)):
    joinable_tables = get_joinable_tables(base_table)
    joinable_columns = get_columns_from_joinable_tables(joinable_tables)
    for joinable_column in joinable_columns:
        is_on_base_table = joinable_column.table == user_selected_col.table
        is_single_result = not has_multiple_results(joinable_column)
        should_group_by = is_on_base_table || is_single_result
        if (should_group_by):
            group_by_columns.add(joinable_column)
return group_by_columns
```

**Comment by dmos62** [comment]
@mathemancer pointed out in sync that the algorithm is correct. He only noted that `has_multiple_results` is a feature of a table, not a column.

**Comment by dmos62** [comment]
We discussed implementation progress with @mathemancer and discovered that the algorithm needs to be respecified to account for other transforms. More specifically, before we had simplified requirements by saying that, at this time, we'll not support multiple summarization transformations in the same query, but didn't realise that that will break transformations like "select a subset of columns".

```python
def finish_specifying_group_agg_transform(db_query, ix_group_agg_transform):
    group_agg_transform = db_query.transformations[ix_group_agg_transform]
    assert type(group_agg_transform) is SummarizeTransform
    # Each transformation in a query has different input aliases
    input_aliases = db_query.get_input_aliases_for_transformation(ix_group_agg_transform)
    input_aliases_not_in_group_agg = _get_input_aliases_not_in_group_agg(input_aliases, group_agg_transform)
    if not input_aliases_not_in_group_agg:
        # If all input aliases for this transform are mentioned in the group-agg transform spec, we
        # consider it fully specified.
        return group_agg_transform
    # A group-agg transform has a base_grouping_column, or a user-selected input alias around
    # which our suggestions will be based.
    user_selected_alias = group_agg_transform.base_grouping_column
    # When we'll have finished specifying this group-agg transform, each input alias not already
    # mentioned in it, will be added either to its "group by set" or its "aggregate on set"
    aliases_to_be_added_to_group_by = set()
    aliases_to_be_added_to_agg_on = set()
    # Most of logic in the rest of method is around whether or not we can add a given input alias
    # to the "group by set"
    can_we_add_to_group_by = (
        _is_unique_constrained(db_query, user_selected_alias)
        and _is_not_generated_via_aggregation(user_selected_alias)
    )
    if can_we_add_to_group_by:
        oids_of_joinable_tables_with_single_results = \
            _get_oids_of_joinable_tables_with_single_results(db_query, engine, metadata)
        oid_of_user_selected_alias = _get_oid_of_alias(db_query, user_selected_alias)
        for input_alias in input_aliases_not_in_group_agg:
            # Any input alias that cannot be grouped by, will be aggregated on
            if _should_group_by(
                _get_oid_of_alias(input_alias),
                oid_of_user_selected_alias,
                oids_of_joinable_tables_with_single_results,
            ):
                alias_set_to_add_to = aliases_to_be_added_to_group_by
            else:
                alias_set_to_add_to = aliases_to_be_added_to_agg_on
            alias_set_to_add_to.add(initial_column.alias)
    else:
        aliases_to_be_added_to_agg_on = input_aliases_not_in_group_agg
    group_agg_transform = group_agg_transform.add_aliases_to_agg_on(aliases_to_be_added_to_agg_on)
    group_agg_transform = group_agg_transform.add_aliases_to_group_by(aliases_to_be_added_to_group_by)
    return group_agg_transform

```

The central change is the `db_query.get_input_aliases_for_transformation(ix_of_transformation)` method that tells you what the input aliases are for a given transformation in the query's transformation pipeline.
