### ISSUE TITLE
Typecating column to JSON_List/Map doesn't work.

### ISSUE THREAD

**Issue by Anish9901** [centerofci/mathesar#1955]
## To Reproduce

1. Create an empty table.
2. Create a new column and add a JSON array to it.
3.  Try to typecast the column to JSON List.
4. Notice there is no error/change to the data type of the column.

## Additional context

![Screenshot from 2022-11-19 22-09-51](https://user-images.githubusercontent.com/52523023/202862061-f447aeb4-9af0-4054-b398-f3288ba50a5c.png)

**Comment by mathemancer** [comment]
This is happening for both our custom JSON List and Json Object Map. The reason the casting isn't working is that the front end isn't submitting the proper type name, prefixed with the `mathesar_types` namespace. See the difference with `mathesar_types.email` for an example. 

As for the back end, we should certainly be throwing an error when a request to change to a type we don't know is submitted, rather than failing silently.
