### ISSUE TITLE
Create a Column API

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#199]
**Problem**

We need to have a column API to operate on columns in the DB:
- Create new columns
- Delete columns
- Edit column names
- Edit column type
- Edit column parameters:
  - default value
  - nullable
  - unique 

**Proposed solution**

We should create API endpoints to allow the operations above to be performed. Ideally, we would follow the pattern of the records API and treat `Column` as a resource to add/edit/delete.

**Additional context**

- Editing column type should only support the types that we already support in our infer types function. See #91.
- We should ensure that we can cast to a specific type before changing a column to it. Also see #91.
- Editing column names blocked by #198

We need to define what the Column API would look like. Please write a technical spec on the wiki's [Architecture section](https://wiki.mathesar.org/engineering/architecture) and get some feedback from @kgodey and @mathemancer before implementing this issue.

**Comment by mathemancer** [comment]
@kgodey Are you sure we need a Column model?  There isn't a global id for columns in the DB, and in fact, the only way to alter a column is via an `ALTER TABLE` statement.  Why would we need to be able to list and manipulate columns outside the context of dealing with their containing table?  If we don't need to do that, what value does the model bring?

**Comment by kgodey** [comment]
@mathemancer I think in terms of resources while designing a REST API. Columns seem like a resource to me – we want to be able to add columns, edit columns, and delete columns.

I don't think we need to operate on them outside of their containing table, so I'd structure the API similar to the current Record API (i.e. `/api/v0/tables/<id>/columns/` rather than `/api/v0/columns/`).

**Comment by mathemancer** [comment]
Similarly to adding/editing records (for which we don't have or want a model), I think that while it makes sense to have an endpoint, I can't see what we'll get from the model other than something we need to keep in sync with the underlying DB.  Regardless of what the service layer looks like (i.e., whether or not there's a model), we'll need to access the underlying column via its table, and alter it by altering its table.  Even the `fkey` constraints that we could associate with a column if we were to create a model for them are actually constraints on the table containing the column when it comes to looking them up in the DB (or in SQLAlchemy).

In particular, there won't be any information about a column that the service actually "owns", and I can't see a use for having a map from a column to the DB by itself.  Every interaction with a column will actually be an interaction with the table that the column resides in.  Kind of the difference between the concepts "create column" vs. "add column to table".

**Comment by kgodey** [comment]
@mathemancer The only thing we'd get from a model is an ID for the column, which we can use in `/api/v0/tables/<id>/columns/<id>/` type URLs to edit/delete columns.  The difference from records is that records have a primary key that we can use as an ID in the URL (we won't support editing records in tables without a primary key column).

I'm open to other ideas, as I mentioned in the original issue description, I think this issue warrants a technical spec before implementation.

**Comment by mathemancer** [comment]
I see your point about the ID.  I don't think it'll be possible to map it to any consistent ID in the DB layer, though, which would make `id` a bit of a misnomer.  To see this, inspect the `pg_attribute` system catalog table in `psql` using `\d pg_attribute`.  That's the system table where all column info is stored.  Note that the indexes (there isn't a primary key) for that table are the pairs:
- `(attrelid, attname)` -- this is a `table_oid`, `column_name` pair 
- `(attrelid, attnum)` -- this is a `table_oid`, `column_number` pair

This means that we're guaranteed that there's at most one column of a given name in a given table.  But, mapping a service-layer ID to something like a `table_oid`, `column_name` pair will be a problem if we rename the column, but the whole purpose of the endpoint would be for doing things like renaming columns.  Even worse, we'll have no way to notice that a column has been renamed in the underlying DB (in contrast to tables or schemas).  In general, it won't be possible to update the column of a given id in the service if whatever we're using to identify the column in the DB is changed.

If we just want an integer to refer to the column by, the column number (i.e., 0th column, 1st column, etc.) would be about as durable as any map (for example) from some column id to a `table_oid`, `column_name` pair in the column model.

The crux of the problem is that there _isn't_ a consistent id for a column at the DB layer, and imposing one in the service will, in my opinion, add confusion and do more harm than good.

**Comment by kgodey** [comment]
@mathemancer I see your point as well. I've updated the issue above to remove the reference to a Django model under "proposed solution".

The options I see are:
1.  Create a `Column` model in Django with `table_oid, column_name` as unique together, and then just destroy the service-level `Column` instance if it doesn't exist anymore.
  - This option would involve creating/destroying Django `Column` instances when we sync with the DB and things have changed outside of Mathesar.
2. Use the column number as the ID (but this won't work if the operation involves reordering columns)
3. Use the column name as the ID (but this won't work if the operation involves renaming columns)
4. Give up on `Column` as a REST resource.

I like option (1) best, even though it's finicky,  but I'm open to other options, including ones I didn't list above. I'm not sure that it's worth discussing further on this issue, we're treading into technical spec territory and I think it's best to just make the technical spec and ask for feedback when we're working on this issue.

**Comment by mathemancer** [comment]
I agree that deferring till we're at the point of speccing it makes sense.  I'd like to flag one thing I realized  on a dog walk this morning in case I forget later when we get to it:  If we use (3) above, we end up having to change ID (or at least double-check the ID) of every column in a table when we change column orders, rather than just dealing with a single column when we change its name.  So, unless we think of a real advantage to (3) over (1) or (2), I think we should probably throw that one out.

**Comment by pavish** [comment]
@kgodey @mathemancer  The Column API makes perfect sense for maintaining REST API standards.

Based on the UX, the user will make multiple modifications (change names, types etc.,) and then hit save. To make it easier for clients and to avoid multiple updates, I believe we will need another endpoint that batches column updates? Thoughts?

**Comment by mathemancer** [comment]
After trying a couple of implementations, I'm currently experimenting with a model-less endpoint (similar to the records API endpoint).  The only hitch I've run into is that I need one extra piece of info in the `PATCH` request.  Basically, we want to make extra sure that whenever we're altering a column, both the index and the name of the column match our expectations.  This isn't a problem when changing the type, but it implies having an `old_column_name` (or the like) in the request when changing the name.  So, a `PATCH` payload to change the name would look something like:
```json
{
  "name": "new name",
  "old_name": "old name",
  "index": 3
}
```
to alter a column from name `old name` to name `new name`.

**Comment by mathemancer** [comment]
The reason for trying the model-less approach is I found that I kept needing to re-reflect whenever doing anything to a column regardless of whether I kept a model or not, and going without reduces a lot of complexity in the service layer.  The _only_ convincing (to me) argument for keeping a `Column` model is to be able to assign a "UI order" to the columns of a table that isn't stored in the DB.  I think we'd be better off with DB-level views for that, though, so I'm not sure even that's necessary.

**Comment by mathemancer** [comment]
@kgodey Idea:  I _might_ be able to put something together that checks the name in the cache (which will exist, since the entire SQLAlchemy `Table` object is cached, along with its column list) so we can avoid submitting the `old_name` in the request.  What do you think?

**Comment by kgodey** [comment]
@mathemancer I need some information before I can make a recommendation: what URL are you sending the `PATCH` to if you're not using the `Column` model? For records, we're using the record's primary key as the ID in the URL.

**Comment by mathemancer** [comment]
I'm using the index of the column in the column list as the ID.  That's another realization from implementation:  That's the most stable of the identifiers (or at least the most difficult to change).  I read the SQLAlchemy code for table reflection, and realized I was replicating some bits for my column reflection.  The column order in the `Table` object is exactly what comes from the `pg_attribute` table (they're actually reading that table for Postgres).

So, the URL for a given column is:

```
http://localhost:8000/api/v0/tables/1/columns/2/
```
(here the column is the 2nd element of the column list, indexed from zero)

**Comment by pavish** [comment]
We are assigning ids to tables right? Similarly, if we treat columns as resources, we could assign unique ids to them. This would make it rest compliant and resolve the problem we are facing (we wouldn't need old names).

**Comment by kgodey** [comment]
@mathemancer Ah okay, so you're using option #2 from my list above. How will you make reordering columns work with using the column order as the key?

**Comment by mathemancer** [comment]
@pavish A tricky detail is that columns aren't identifiable at the DB level.  You can't tell the difference between renaming a column or deleting it from reflection (i.e., if the change happens in the DB).

**Comment by mathemancer** [comment]
@kgodey If we reorder the columns, we need to do that at the table level regardless (i.e., column order is a property of a table, not of a column).  Or at least that's what I'm thinking.  From that perspective, reordering the columns would be a `PATCH` request to the `tables` endpoint, and the new order will be reflected by the column indices.  I'm trying to be pretty precise here, and avoid using the term `ID` for a column, since it's (as discussed above) a misnomer in this case.

**Comment by kgodey** [comment]
@mathemancer Okay, that makes sense re: column order being the property of a table. Let's go ahead with the checking the name in the cache plan.

If we end up needing to store the Column model in the DB later (for features such as different column orders per user, or column-level privileges, as @pavish pointed out above), we can refactor then.

**Comment by mathemancer** [comment]
> If we end up needing to store the Column model in the DB later (for features such as different column orders per user, or column-level privileges, as @pavish pointed out above), we can refactor then.

Totally happy to refactor when/if we need the extra power.

**Comment by mathemancer** [comment]
@pavish The lack of ID for a column is in contrast to tables and schemata, which receive a DB-wide unique identifier (the `oid`) that we can use to observe whether a table has been renamed (or otherwise altered) or just deleted.

**Comment by pavish** [comment]
@mathemancer I didn't phrase my comment properly. I was supporting option 1 from Kriti's list. Generating a uuid from column name and using it as an id, and storing it on our db.

But your comment on treating column order as a table property makes sense. I would also prefer this to start with. Wouldn't this would also make the column list as a property of the table?

**Comment by mathemancer** [comment]
> But your comment on treating column order as a table property makes sense. I would also prefer this to start with. Wouldn't this would also make the column list as a property of the table?

I think one advantage of just reading the column list from the table property for the `columns` endpoint is that it lets us have both in an easy way.  But, we get the added advantage of being able to use idiomatic(ish) HTTP requests at the `columns` end points to do CRUD stuff to columns.

**Comment by kgodey** [comment]
@pavish We're setting it up as similar to the records API, with the URL being `/api/v0/tables/1/columns/2/`, so columns are intrinsically tied to the tables they're a part of. Things like changing column name and type should go in the Column API, since they don't depend on awareness of any other columns in the table (whereas changing the order does).

**Comment by pavish** [comment]
@kgodey @mathemancer  I agree with changing column names and types should go in the Column API. My question is on the GET of the column list. If order is a property of the table, as it should be, shouldn't the list of columns also be part of the table?

**Comment by pavish** [comment]
@mathemancer @kgodey Thinking again, as per the discussion, if order is to be provided in table GET response, it also means the column id needs to be provided (since id would be the key, and order, the value). Then, we query the columns API separately to fetch the column details of the table. Order would be a property of the table, and each column has it's own set of properties. This is fine by me, and makes more sense, than returning it all on table GET.

**Comment by kgodey** [comment]
@pavish Yeah, that's what I was thinking as well. You only need the column information of the table currently open, and you can get that from a separate API call to the column list API. For example, the table list API does not need all the column information of all the tables.

**Comment by pavish** [comment]
@kgodey Yeah, makes a lot of sense.

I was just wondering if we could have a separate endpoint that returns the joined result of tables and columns. Since this would be a common usecase for any client using Mathesar's APIs. 

Any internal resource sucha as Schemas, Tables and Columns would work the same way as we query data from a table i.e we should be able to join them through our APIs. Thoughts?

**Comment by kgodey** [comment]
@pavish I'm not sure what you mean by "joined result" (or joining resources), could you elaborate?

**Comment by pavish** [comment]
This was what I had in mind:

There's a parent table, and a child table which references the parent.

parent:
```
id
name
```

child:
```
child_id
child_name
parent
```

When joining them, the result would be records with:
`id, name, child_id, child_name, parent`

Here id and name would be repeated several times.
This is a good way to show on the UI, and the way records are returned from databases.

As an API definition, wouldn't it be better to also have an additional option to return the joined records as:

```
{
  id,
  name,
  child: [
    {
      child_id,
      child_name
    }
  ]
}
```

Of course, this wouldn't work well with pagination or any database operations. A fleeting thought out of my mind.

**Comment by mathemancer** [comment]
Isn't this kind of what we have now, though?  I.e., in the `schemas` endpoint, each schema's tables are listed (without all details).  Then in the `tables` endpoint, each table's columns are listed (without all details).  Or are you talking about having a general `join` operator so we can do the same with the user's data tables?

**Comment by pavish** [comment]
I'm thinking of a general join, to do it for all tables (user data tables / internal tables). I believe I'm just describing graphql at this point.

**Comment by kgodey** [comment]
@pavish I was just typing a comment about how you seem to be describing GraphQL. We can consider setting up a GraphQL API for Mathesar after the MVP. If you want to make an issue for it, go ahead and I'll put it on our "Future" board.

**Comment by mathemancer** [comment]
As per discussions on the matrix channel, we're going to wait for the uniqueness constraint changing until a later date.
