### ISSUE TITLE
Grouped table page breaks when filter yields no results

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2005]
## To reproduce
1. Set up a table with column with data type `Number` (DB type `NUMERIC`, the default)
2. Group by some columns
3. Try filtering like so
![Screen Shot 2022-11-30 at 11 46 00 PM](https://user-images.githubusercontent.com/287034/204967871-02dd2b82-3a5d-4112-870d-17b692bfb8ec.png)
4. Observe that the table becomes full of `DEFAULT` values
![Screenshot 2022-11-30 at 23-46-57 Cycle 6 Work Team Workflow Mathesar](https://user-images.githubusercontent.com/287034/204967975-7f7c8fff-9a12-4066-ad07-f146a99ce851.png)

## Context
- There is no API error
- "Greater than" or "Greater than or equal to" filters work as expected

## Cause
- When there are no results returned from a filter, when grouping is also present, it results in this state.

**Comment by seancolsen** [comment]
- This is the records API response when table page is filtered and _not_ grouped. The page works fine here.

    ```json
    {
      "count": 0,
      "grouping": null,
      "preview_data": null,
      "results": []
    }
    ```

- This is the records API response when the table page is filtered _and_ grouped. The API response looks fine to me, but the page is broken in exactly the manner described by Kriti.

    ```json
    {
      "count": 0,
      "grouping": {
        "columns": [
          59
        ],
        "mode": "distinct",
        "num_groups": null,
        "bound_tuples": null,
        "count_by": null,
        "global_min": null,
        "global_max": null,
        "preproc": null,
        "prefix_length": null,
        "extract_field": null,
        "ranged": false,
        "groups": null
      },
      "preview_data": null,
      "results": []
    }
    ```

This seems like a front-end-only issue to me that has something to do with grouping. I'm going to take this up

**Comment by pavish** [comment]
> This seems like a front-end-only issue to me that has something to do with grouping

This again is an issue with the backend returning `null` instead of empty arrays, in this case, it's for `grouping.groups`. Previously, we used to get only empty arrays and the frontend does not handle `null`. This change has been made on several APIs, I'm not sure when, but the frontend hasn't handled it. I noticed a few cases while working on Data explorer and handled `null`, I'm not sure if we have any more.

I do think the backend should always send an empty array for array types in json, instead of null.

**Comment by seancolsen** [comment]
Thanks for pointing that out, @pavish. I misunderstood your previous commend, because I thought you were referring to the `results` property of the API response. I've opened #2340 with a quick front end fix to handle a `null` value here. Seeing types like `T[] | null` does irk me, but I'm not sure it's worth opening another ticket to make the backend changes here. Any opinions, @kgodey?

**Comment by kgodey** [comment]
If there's a backend ticket for this, I would put it in the Icebox milestone. It might make a good ticket for community contributors. Otherwise, I have no opinion.
