### ISSUE TITLE
Context menu for column headers

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2013]
From [Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1304%3A7357&t=vgrYQ3QETzQgwMcf-0):

![image](https://user-images.githubusercontent.com/42411/210856117-360ca4f2-9f50-4c44-bd61-8e17c4d29fbe.png)

**Comment by seancolsen** [comment]
I would like to combine this ticket with #2014 and add some more detail. @rajatvijay what exactly would you like to put into these menus? I have some thing that I'd like to see in these menus, and I want to make sure we're all on the same page before heading into implementation.

**Comment by kgodey** [comment]
@seancolsen Context menus are defined in the Table Page [Figma design](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1304%3A7357&t=ksOye46ThtSxLqDC-0) – see "menus". This and #2014 was originally part of the Table Page styling issue but was split off.

**Comment by seancolsen** [comment]
Thanks for clarifying, @kgodey. I've updated the ticket description to link to Figma. Let's keep this ticket separate from #2014

**Comment by seancolsen** [comment]
Design question:

When one sorting condition is already applied, what happens when I apply a second one?

- (A) the new sorting condition is **prepended** to the existing conditions, added with highest precedence
- (B) the new sorting condition is **appended** to the existing conditions, added with lowest precedence
- (C) the new sorting condition **replaces** all the existing conditions

In a [Matrix conversation](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$_SY_KA04MVxJ9jq7EDITmOGmipJvI2th_Sdn9XhuWMk?via=matrix.mathesar.org&via=matrix.org):

- Sean said that spreadsheets use behavior (A)
- Sean and Pavish said they want behavior (B)
- Rajat said he wants behavior (C)

**Comment by ghislaineguerin** [comment]
I think (B) keeps the order more clear, but makes it harder for users to change the highest precedence. I wonder if we should have an option to remove all sorting so that users can have an easy way to accomplish both goals.

**Comment by kgodey** [comment]
(B) makes the most sense to me. We have a UI for showing sort precedence that the user can use (the button in the table header), and it doesn't make sense to entirely replace sorting when the user can easily see what sorting has been applied.

After release, I think we can make improvements like adding a "remove all sorting" option and maybe copy updates that make the precedence more clear. I don't think it's worth spending more time on right now, though.
