### ISSUE TITLE
Aggregated results contains duplicates when joining multiple tables

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2059]
* Create an exploration with 'Patrons' as the base table
* Add 'Email' from 'Patrons' table
* Add 'Title' from 'Publications' table
* Add 'Due Date' from 'Checkouts' table
* Summarize by 'Patrons_Email'

**Expect the result to contain unique values in the Publications_Title aggregated list. Notice that it contains duplicates.**

![Screenshot 2022-12-09 at 2 14 56 AM](https://user-images.githubusercontent.com/11850603/206563767-a6b36d75-8ce5-44c3-93a1-6e9de95dc2d0.png)

**Comment by mathemancer** [comment]
This is because aggregation to an array doesn't remove duplicates. We'd want to aggregate distinct values to an array. I can't see a downside of changing that logic at the moment, and the change should be easy/quick.

**Comment by seancolsen** [comment]
I mentioned this in my [Data Explorer usability testing](https://gist.github.com/seancolsen/323169d337a1be4ee342cffd631b9a06):

> (24) I want to be able to configure the DISTINCT and ORDER BY behavior of ARRAY_AGG.

@mathemancer said: 

> I can't see a downside of changing that logic at the moment

One downside is that in some (perhaps rare) cases the count of values might not agree with the user's expectation. It would be nice to give the user control over `DISTINCT` and `ORDER BY`, most likely using `DISTINCT` by default. I can appreciate that the additional UX challenges that we'd need to solve for that, so I support adding `DISTINCT` for now. If we do, it might be nice to alter the UI to add the word "distinct", i.e. _"9 distinct values"_ instead of _"9 values"_.
