### ISSUE TITLE
Document pre-commit linter hook

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#21]
We should make a document to help contributors optionally set up a pre-commit hook with the same linting that we're using in the repo.  This will let them have a quick check on each commit rather than waiting till they submit a PR to see if it's going to pass the linter without problems.

**Comment by dhruvkb** [comment]
This issue seems like a good one to start with. Can I work on it?

**Comment by mathemancer** [comment]
Please do, thanks!

**Comment by dhruvkb** [comment]
Did some work on this and I'm running into a bit of a dillemma.

- The top-level Django codebase can run Flake8 on the pre-commit hook (managed by [`pre-commit`](https://pre-commit.com)).
- The inner Svelte codebase can run `npm run lint` on the pre-commit hook (managed by [`husky`](https://typicode.github.io/husky)).

Git only allows one script on the pre-commit hook so
- We cannot use both the above packages because they overwrite each other's scripts in the `.git/hooks/` directory.
- Any complete script for linting would have to lint both Python with Flake8 and JavaScript with ESLint regardless of which code has actually changed, which takes slightly longer.

The less-pleasant alternative is to have two separate hooks and let the devs choose which code they'd primarily be working on and only setup the hooks for that particular codebase.

**Comment by kgodey** [comment]
@dhruvkb Could you write a custom bash script that runs both? See [this Stack Overflow question](https://stackoverflow.com/questions/30104343/multiple-git-hooks-for-the-same-trigger).

I'm not sure that we need to install either package, just provide a script and add instructions in the `README` for how to set up the script.

**Comment by dhruvkb** [comment]
Yeah the only issue with a script that lints both Python and JS is that we'd be linting a lot of untouched code.

**Comment by kgodey** [comment]
I think that's fine.
