### ISSUE TITLE
ID sequence isn't being created for tables

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2144]
## Description

I cannot add a new record to a new table because the ID does not have a default value. I set up this table by:
1. Importing [library_books.tsv.zip](https://github.com/centerofci/mathesar/files/10273401/library_books.tsv.zip) as "Items"
2. Pulling "Author First Name" and "Author First Name" into an "Authors" table
3. Moving "Author Website" to "Authors" table
4. Pulling "Publishers" into a "Publishers" table
5. Pulling "Title", "Publication Year", "ISBN", "Authors_id", and "Publishers_id" into a "Books" table

## Expected behavior

I should be able to add a new record!

## To Reproduce

~Try adding a new record on https://library.mathesar.org/mathesar_tables/4/tables/34/~

I needed to nuke this table since it was blocking my work. To reproduce, follow the steps under Description.

## Additional context

This seems related to
- #2116 
- #1356

**Comment by kgodey** [comment]
Also, after creating a Checkouts table manually, when I tried to run:

`psql -d mathesar -f 02_add_checkouts.sql`

I got

`ERROR:  relation "Library Management.Checkouts_id_seq" does not exist`

**Comment by mathemancer** [comment]
As for the second error, that's expected (and unavoidable). It's not possible to combine manually-created tables with the auto-loading SQL, since the names of (in this case) sequences may not be the same and we need to be able to modify those in the auto-loading SQL. In this case, it likely failed when it tried to reset the sequence so that ID numbers of checkouts would work.

**Comment by mathemancer** [comment]
The first error (the sequences being incorrect after splitting) is difficult, and I can't believe we've missed it for this long.

It seems that when we split a table, the created new table ("Authors") has a primary key column associated with a sequence to generate integer IDs. The insert logic that adds records to the extracted table doesn't increment the sequence at all, and there's no logic to update the sequence's current value. Thus, when you try to insert into such a table, you have a clash since the sequence generates a 'new' id of `1`, which already exists in the table.

We need to add logic to set the sequence associated with the primary key to the maximum value of the table (or max + 1, depending what params SQLAlchemy supports)

**Comment by kgodey** [comment]
This is not fixed. Try inserting an item into https://library.mathesar.org/mathesar_tables/74/tables/160/. I deployed the new code, deleted the schema, re-imported the data and split the tables.

Please note that I'm unable to add records to the _original_ table ("Items"), not the table that was extracted ("Authors"). @mathemancer's explanation seems to work for "Authors" (and I can confirm that I can add a record to "Authors") but not for the original table.

**Comment by silentninja** [comment]
The problem occurs when an imported dataset has an existing `id` column. We don't set defaults to the `id` column if it is part of the dataset and isn't created by Mathesar.
https://github.com/centerofci/mathesar/blob/6069c4daace882d803b59f499a83b0606714afee/db/columns/utils.py#L43

So we need to remove the `id` column from the `library_books.tsv` dataset or set the above line to `True`

**Comment by kgodey** [comment]
Okay we can remove the column in the file for the video. Thanks for getting to the bottom of this.

**Comment by kgodey** [comment]
I think this is a blocker for usability testing since it means that if anyone uploads a file with an `id` column, the table won't allow any further operations and will fail mysteriously. @silentninja please prioritize this.

**Comment by kgodey** [comment]
I've moved this to launch blockers since we can design usability tests to work around this. This is still a blocker to launch or sharing the demo website widely.
