### ISSUE TITLE
Something is wrong with the data explorer....

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2145]
I'm trying to make the Overdue Books report and ended up with this:
<img width="1151" alt="Screen Shot 2022-12-20 at 7 23 10 PM" src="https://user-images.githubusercontent.com/287034/208792427-f8b7bc2a-7228-4c11-90d0-d95766bcd7e4.png">

Aaron Black has not checked out the same book over and over again, here's what his checkouts actually look like.
![Screenshot 2022-12-20 at 19-27-52 Checkouts Library Management Mathesar](https://user-images.githubusercontent.com/287034/208792546-da7f06f7-1adc-4f04-879a-23de904da309.png)

If I try to recreate the exploration, everything looks fine - I add Patron name, email, and book title (I selected do not summarize) and get this:
![Screenshot 2022-12-20 at 19-29-36 Data Explorer Library Management Mathesar](https://user-images.githubusercontent.com/287034/208792856-46012765-44e5-4c9d-8e61-aa91329bfbb4.png)

Then I add Due Date from Checkouts and everything goes nuts

![Screenshot 2022-12-20 at 19-30-01 Data Explorer Library Management Mathesar](https://user-images.githubusercontent.com/287034/208792901-6d923733-569d-464b-9da4-691b33955c75.png)

**Comment by pavish** [comment]
This is a backend bug. Multiple rows are being returned by the API. @dmos62

**Comment by dmos62** [comment]
Hm, given base table `Patrons`, if you pull in as initial columns Patron id, and Checkout id twice, you'd expect both Checkout id columns to be identical, but they're not, and when the second one is added, the number of records goes from 105 to 471. 

![2022-12-21_15-31](https://user-images.githubusercontent.com/2715476/208917432-be1814e4-3af8-4691-ac95-a9287910c20c.png)

**Comment by pavish** [comment]
I think the result of the current query makes sense from an sql perspective. We need to update the query to suit the behaviour we want.

In the mentioned query, 
When the base table is Checkouts:
* Assume we have 100 checkouts and we add columns from the checkouts table. There are now 100 rows, one checkout per result row.
* Assume we have 2 checkouts per patron.
* When performing the first join with Patrons, the result still contains 100 rows, with one checkout per result row. The join is made from checkouts to patrons, resulting in 1 associated patron per row. The patron columns may be duplicated but the row count will remain 100.
* When performing the second join with Patrons, it results in the same 100 rows, since the previous result has 100 rows.

When the base table is Patrons:
* Assume we have 10 patrons and we add columns from the patrons table. We have 10 rows, 1 unique patron per result row.
* Assume we have 2 checkouts per patron.
* We now perform the first join with Checkouts, the result contains 200 rows (100 * 2), with Patrons duplicated twice per result row, because the checkout is unique.
* We perform the second join with Checkouts, which happens on the previous result with 200 rows, which joins with the patron id from each of the 200 result rows, resulting in 200 * 2 = 400 rows.

**Comment by silentninja** [comment]
> -    public."Checkouts" 
> -    LEFT OUTER JOIN public."Patrons" AS "Patrons_1" ON public."Checkouts"."Patron" = "Patrons_1".id 
> -    LEFT OUTER JOIN public."Patrons" AS "Patrons_2" ON public."Checkouts"."Patron" = "Patrons_2".id
@dmos62 It is working as expected, a Patron can have more than one checkout and since you are doing multiple join, each of the joins refers to any one of the checkouts associated with the Patron.

**Comment by kgodey** [comment]
This is working properly now, nice work @pavish!

**Comment by pavish** [comment]
@kgodey 

> Summarize based on patron email (there should be LESS than 180 rows at this point, and only "Book Title" should show up as a List)

For this point, we'd expect patron first name and last name to be part of the grouped columns, instead they are getting aggregated as list. Summarization suggestion aggregates them instead of grouping.

Currently, the list has a single value but it's still an array column so it appears inside a pill, which looks like this:
![Screenshot 2022-12-22 at 8 47 29 AM](https://user-images.githubusercontent.com/11850603/209048160-425bcbd6-38d1-41ed-af12-ec98e35f5816.png)

What we'd expect is this:
![Screenshot 2022-12-22 at 8 47 45 AM](https://user-images.githubusercontent.com/11850603/209048184-d86308c9-1775-4edd-8928-57c697053f87.png)

I've created an issue: https://github.com/centerofci/mathesar/issues/2157 for this. I'm not certain if it's needed for the demo video, can you take a look?

**Comment by kgodey** [comment]
@pavish I commented on the issue. We can work around it for the video if needed but it would be nice to have so we don't have to.
