### ISSUE TITLE
Compress static assets while serving

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2204]
## Description
* Our frontend static assets are being served as is, in production mode. This leads to a higher loading time.
* They need to be served with gzip compression.
* ~For User-Agents that support brotli, they need to be compressed with brotli~ (branched off to a separate issue: https://github.com/centerofci/mathesar/issues/2411).

**Comment by IyadElwy** [comment]
Hey! I'd like to tackle this issue if that's alright.
If I misunderstand anything please do correct me, but I think this could be resolved by:

1. Identifying the User-Agent and their supported compression types
2. Add the logic for compression
3. adjust the build command so that anytime we build, the static files are compressed first
4. Check performance using Chrome's Lighthouse scores

To be on the safe side, this issue is labeled as backend so which assets are you referring to here?

**Comment by pavish** [comment]
@IyadElwy Compression for the static files needs to be enabled on the webserver, so this is tagged as backend work. This is not something we'd want to do during frontend build time (expect perhaps brotli, but that's a lower priority).

This issue deals with enabling compression in our production setup with the webserver we use, which I believe is Gunicorn.

Since this involves our production & deployment setup, this issue is currently restricted to maintainers. I've missed tagging it as such. Please feel free to pick another issue that interests you.

**Comment by dmos62** [comment]
Opened a PR for compressing on the fly: https://github.com/centerofci/mathesar/pull/2410

Branching out the Brotli/precompression requirement into a separate issue: https://github.com/centerofci/mathesar/issues/2411

Editing the description of this ticket to not require Brotli.
