### ISSUE TITLE
API to delete records in bulk

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2237]
### Description
* We allow users to allow deleting multiple records together using our UI
* Currently, we make a delete request for each of those records, which leads to an unstable UX, since we need to keep track of which ones succeeded and which didnt and show messages accordingly
* An API to handle this in a single transaction would avoid UI & UX complexity

Related:
* https://github.com/centerofci/mathesar/issues/2233

**Comment by aagman945** [comment]
I would like to work on this

**Comment by kgodey** [comment]
Sure @aagman945. Please propose the new API structure in this issue for approval before implementing it.

**Comment by aagman945** [comment]
We have 2 ways here.
1) Update current destory method in `RecordViewSet` , allow multiple pks, loop over each and delete record
2) To create new delete action for bulk delete.
 In either case we have to return response with success and failure of each deletion.

**Comment by kgodey** [comment]
We should have a new bulk delete action (option 2). 

Could you describe:
1. what the URL would be
2. what a request body would look like
3. what the response body would look like

**Comment by aagman945** [comment]
1)  `http://localhost:8000/api/db/v0/tables/1/records/bulk_delete/`
2) request body should should  have list of pks
3)  response body {pk: error response following to our [error standards](https://wiki.mathesar.org/en/engineering/standards/api#errors)}
response will only contain exceptions for failed cases

**Comment by mathemancer** [comment]
I think it would be much cleaner (and better data management) to do this atomically. I.e., either the whole bulk delete would work, or it wouldn't. This would also be the most performant option. This would require changing (3), since we'd only get feedback from the DB about one record (that couldn't be deleted). I don't think we need `bulk` in (1), rather a simple `http://localhost:8000/api/ui/v0/tables/1/records/delete/` . I also think it might make sense to use the `/ui/` section of the API (@kgodey what do you think?). (2) makes sense to me.

**Comment by kgodey** [comment]
I agree with you on all points, @mathemancer. @aagman945 Can you submit a new plan based on @mathemancer's feedback?

**Comment by aagman945** [comment]
1. endpoint `http://localhost:8000/api/ui/v0/tables/1/records/delete/`
2. create new operation for bulk delete
3. return 204 if successfull or raise error
