### ISSUE TITLE
Users & permission frontend improvements

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2432]
### Notes
- This issue was pulled out of #2205 
- [Figma link for design](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=3666%3A25085&t=8OQlup2xkwSzgEP5-0)
- RFC for implementation details: [PR link](https://github.com/centerofci/mathesar-wiki/pull/75) (will be replaced by wiki link once merged)

### Tasks
- [ ] #2555
- [ ] #2556

**Comment by IamEzio** [comment]
Hi @kgodey, can I work on this issue? Thanks!

**Comment by kgodey** [comment]
@IamEzio sure! I'd recommend starting with one of the three items in the issue rather than tackling them all at once.

**Comment by varun7singh** [comment]
hi @kgodey  can i work on the client side validation task

**Comment by kgodey** [comment]
sure @varun7singh. @IamEzio which one are you working on?

**Comment by IamEzio** [comment]
I am working on the first task, i.e,  `Add client side validations for email, username, password length`.

**Comment by varun7singh** [comment]
okay i'll work on another issue @IamEzio

**Comment by IamEzio** [comment]
@kgodey could you please provide me all the parameters against which I should validate username and password? It would be great if there is a doc with all such rules. Thanks!

**Comment by kgodey** [comment]
@IamEzio We don't have a list of parameters, but we're using default Django settings. @pavish might have more thoughts since he wrote the original ticket.

**Comment by pavish** [comment]
Sorry for the delayed response, I missed this as I was occupied with release work.

@IamEzio I do not have any specific criteria at the moment. The backend follows the default Django settings.

Part of fixing this issue is finding the default settings & criteria Django uses, and identifying those that can be validated on the frontend. Once you have that figured out, please add a comment to the ticket, get an approval from one of us on the core team, and implement it.

**Comment by pavish** [comment]
I'm closing this issue, since I don't think it needs tracking as a meta ticket.

**Comment by varun7singh** [comment]
hi @pavish  sorry for the late reply im currently working on #2355  Thanks.
