### ISSUE TITLE
Bug when adding and deleting rows.

### ISSUE THREAD

**Issue by thesujai** [centerofci/mathesar#2463]
## Description

Weird bugs while adding new rows and deleting them in the table.
When we add more that 2 new rows in the table at once, and then try to fill it it works. But deleting any row after these operation causes the page to buffer. Though we find the row deleted when we refresh the page.

## Expected behavior

There should be no infinite buffering when deleting rows after adding many of them.

## To Reproduce

I am attaching a video:
[Screencast from 13-02-23 01:10:04 AM IST.webm](https://user-images.githubusercontent.com/120925871/218361008-d44a2c05-d26f-412a-a8dc-242699a2128e.webm)

**Comment by thesujai** [comment]
cc @pavish

**Comment by silentninja** [comment]
@thesujai Thanks for reporting the bug!

**Comment by pavish** [comment]
I removed the backend tag, since I can confirm that this is a frontend bug.

For those interested, the root cause is that the `deleteSelected` function in `/stores/table-data/records.ts` sets the `savedRecords` store with the latest data fetched from server and then updates the `newRecords` store to remove saved records from it, which results in duplicates. The removal from `newRecords` needs to happen before fetching the latest data.

I am restricted this to maintainers since this is a high priority.

@kgodey I would also like to place this within `0.1.1`.
