### ISSUE TITLE
Implementation for Number data types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#248]
## Problem

Users will want to store numeric data in columns. We should allow them to do so and implement this type appropriately in the backend.

## Proposed solution

We should support Number types in Mathesar and allow users to use them.

Tasks that need to completed:
- [x] #238 
- [x] #377
- [x] #378
- [x] #379
- [x] #380
- [x] #381
- [x] #382
- [x] #383
- [x] #434
- [x] #385
- [x] #384
- [x] #386
- [x] #258 

## Additional context
Related issues:
- #269
- #127 
- #135

**Comment by mathemancer** [comment]
I think we should split out a separate issue for `NUMERIC` types with arguments to support the "decimal" type with specified decimal points, etc.

I also think we should split out different issues for each underlying DB type:

- `REAL`
- `DOUBLE PRECISION`
- `SMALLINT`
- `INTEGER`
- `BIGINT`

We should also have a separate issue for the percentage type¸ since that will require a custom type at the DB level, unlike the other types called for.

**Comment by kgodey** [comment]
@mathemancer I've split up the issues. I asked you a question on #386.
