### ISSUE TITLE
Test upgrades and make sure they work

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2534]
### Preparation
- [x] Make sure there are two releases (both on Github and Dockerhub) - @dmos62
  - with different versions strigs/tags in code, in git and in docker
- [x] Figure out steps to switch between releases in dev - @dmos62 
  - so that we can trigger in-app updating and then "rewind"

## Testing process
- [x] Call the upgrade endpoint to double-check that it still works - @dmos62 
- [x] Install first release locally and test upgrade - @dmos62 
- [x] Install first release locally and test upgrade - @pavish

**Comment by dmos62** [comment]
The releases are published on Github and pushed to Dockerhub.

The steps to pull down and switch between releases:

1. Delete your docker volumes (Mathesar related), so as to not conflict with prod installation
2. [Install Mathesar via `install.sh`](https://docs.mathesar.org/installation/docker-compose/#)
3. Go to http://localhost/administration/update/ to check that your version is `0.0.3`
  - If it's not, someone may have pushed a new image with the old version string
5. Go to `/etc/mathesar/` (that's where your `docker-compose.yml` is found by default)
6. Do `docker-compose --profile prod down` to bring Mathesar down
7. Do `sudo docker rm (sudo docker ps -a -q)` to remove all containers (will also remove non-Mathesar containers)
8. Pull down an earlier release with `docker pull mathesar/mathesar-prod:0.0.2`
9. Make sure it's tagged with `latest`: `sudo docker tag mathesar/mathesar-prod:0.0.2 mathesar/mathesar-prod:latest`
10. Do `sudo docker image ls` to make sure that the `0.0.2` is tagged with `latest` and it's indeed the most recent image you have (topmost);
  - if it's not, get rid of those other images so that it is
11. Do `docker-compose --profile prod up` to bring Mathesar up
12. Go to http://localhost/administration/update/ to check that your version is `0.0.2`
  - You should see that an update to `0.0.3` is available and have option to update.

To repeatedly test upgrading, repeat steps 6-12.

**Comment by dmos62** [comment]
A bug was discovered: https://github.com/centerofci/mathesar/issues/2566

**Comment by pavish** [comment]
@kgodey @dmos62 

I faced some installation difficulties yesterday on my mac and didn't want to mess up my dev env, so I tested this out on my old linux machine and upgrades worked, except for the issue @dmos62 reported.

I tried to perform installation and upgrade on my mac today to do a more thorough testing and fix #2566, and nothing worked. The installation failed and the images we have on dockerhub are all `amd` so it's not possible to ever run them on my mac-M1 which has an `arm` architecture.

I built our images from scratch and ran it locally in prod mode, but the upgrades wont work because the image son dockerhub are of amd architecture.

I can raise a PR for #2566 but I won't be able to test it on my dev env, it might be better for someone else to pick that up.

**Comment by pavish** [comment]
I've tested this multiple times on both a Linux machine - ubuntu 22.04, and a Mac - M1 - Apple silicon - Big Sur.

This works as expected. I've had to push additional images to our dockerhub to make this work on arm64.

I've also fixed #2566 in the PR https://github.com/centerofci/mathesar/pull/2577. The image 0.0.2 on the dockerhub already contains this fix, and I've tested upgrades on it as well.

I did not perform any aggressive testing such as intentionally crashing the service to check recoverability.

**Comment by pavish** [comment]
@kgodey I've leave it upto you to take a look at the comments and close the issue.

**Comment by kgodey** [comment]
I'll leave it open until we re-test, @pavish.

**Comment by dmos62** [comment]
We've now tested this multiple times.
