### ISSUE TITLE
Fix demo mode

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2559]
Demo templating code was accidentally deleted and now demo mode is broken.

**Comment by dmos62** [comment]
I might be out of the loop here, but deleting that wasn't an accident. I moved the template setup logic to a Django management command so that we can perform the setup when, and only when, first setting up the demo server (somehow that setup hook was being called at unexpected times and redundantly).

**Comment by kgodey** [comment]
Description isn't meant to be accurate, it's just a placeholder so we don't forget about the issue. @mathemancer knows what the details are.

**Comment by dmos62** [comment]
That's fine. Just making sure code intent is clear. Here's the PR for context: #2491.

**Comment by mathemancer** [comment]
Okay, talked with @dmos62 about this on Matrix, and he reminded me / clarified a few things.

We'll handle this with documentation for now. It's not worth the potential bug introduction to add this to a run script or the dev mode in general. Also (I'd forgotten), the relevant management command `setup_demo_template_db` is being run by the ansible playbook for demo mode already.
