### ISSUE TITLE
Empty column mapped to boolean

### ISSUE THREAD

**Issue by frafra** [centerofci/mathesar#2657]
## Description
Empty columns are set as boolean.
I found no way to change the default/fallback type to text.

## Expected behavior
I would expect using a more relaxed type, as text, since there is no information to infer the type.

## To Reproduce
Import a CSV with an empty column.

**Comment by kgodey** [comment]
Thank you for reporting this, @frafra. The intended behavior is that text should be the default type, and there should be a way to change any column's type to text. We'll fix this.

**Comment by mathemancer** [comment]
Hrm. There _is_ a way to change the actual column type to text, and it is the default. The problem is that `NULL` is a valid value in a boolean column. Changing that would mean that no column with a `NULL` value somewhere could be inferred to be boolean (or indeed cast to boolean using our current setup). 

@kgodey I think we'll have to wait till we're using a global view of columns during type inference to fix this. I.e., we'd have to know that _all_ values are `NULL` to short-circuit the inference logic.

**Comment by kgodey** [comment]
@mathemancer I think the issue here is that the "default" type for inference should be Text, not Boolean. Can we not change the order of inferred types so we prefer Text to Boolean?

I think it's okay if we don't infer booleans correctly (we can fix that in a future issue), that seems preferable to setting empty columns as booleans by default.

**Comment by mathemancer** [comment]
> @mathemancer I think the issue here is that the "default" type for inference should be Text, not Boolean. Can we not change the order of inferred types so we prefer Text to Boolean?
> 
> I think it's okay if we don't infer booleans correctly (we can fix that in a future issue), that seems preferable to setting empty columns as booleans by default.

I understand the issue perfectly.

I'll explain our inference logic a bit. Perhaps that will help.

We don't have any global view of a column when doing type inference. Our 'inference' concept is rather 'can I cast this column to `<some_type>`?'. If so, we accept the column as a `<some_type>`, and otherwise we don't. We proceed through various types in order, and exit which we find one where the casting process is successful. It's important to understand this detail. We aren't comparing a couple of potential casting results in some way and deciding which is 'better' by some metric. We're simply checking whether we can do a given casting at all, and _the first valid target type found_ is the inferred type.

Note that the casting logic can only see one value at a time. So, testing whether you can cast a column to `BOOLEAN` amounts to testing whether we can cast each value in the column, individually, to a `BOOLEAN`. Since `NULL` is a valid value to be cast to type `BOOLEAN` (and in fact is a valid value to be cast to any type; more on that later), we have a problem when all values of a column are `NULL` (i.e., if it's an empty column), since the test 'can I cast the column to `BOOLEAN`' will return `true`. Further, any logic which takes into account the fact that all values in a column are `NULL` is global by definition (in this context).

Now, _any_ value can be cast to `TEXT`. In fact, we start by importing the data with all columns initially as `TEXT` columns. Thus, we would never test any type which occurs after `TEXT` in the hierarchy at all. Some implications:
- Moving `BOOLEAN` after `TEXT` in the testing order means we'd never infer any column to be a `BOOLEAN`.
- We'd (with our current order) instead infer it to be the type `MATHESAR_TYPES.EMAIL` (which is arguably more confusing than `BOOLEAN`).
- If we instead move `TEXT` to the front of the testing order, then we will only ever infer a column to be of type `TEXT`. I.e., we'd disable the type inference logic entirely.

The other non-global option I can think of is to change our `cast_to_boolean` function to disallow `NULL` values. This would mean (as mentioned previously) that no column with any `NULL` value could be cast to `BOOLEAN` in Mathesar. I think this would be considerably worse than having the inference logic return `BOOLEAN` for an empty column.

All that said, I think this might be a case to add some ad-hoc global inference logic, basically the simple rule
```
(all NULL) -> TEXT
```
I strongly suggest we resist the urge to add global type inference logic in an ad-hoc fashion in the future, since that's complicated stuff, and the maintenance and testing burden would be considerable.

**Comment by frafra** [comment]
Do not cast (thus use the default TEXT) if no data is available, seems the only reasonable solution. Doing it efficiently could be challenging, but that would not mean that mathesar would begin to implement an entirely new class of global type interference procedures.

**Comment by mathemancer** [comment]
> Do not cast (thus use the default TEXT) if no data is available, seems the only reasonable solution. Doing it efficiently could be challenging, but that would not mean that mathesar would begin to implement an entirely new class of global type interference procedures.

That's the plan. We'll implement this logic ad-hoc as a check for each column before doing the inference logic. It will be precisely as efficient as checking `EXISTS (SELECT 1 FROM mytable WHERE mycol IS NOT NULL)` for an unidexed column.

Some context for future historians: "Global inference logic" in this context refers to any logic that takes into account the data (or in this case lack of it) for an entire column when determining its likely type. We've had a number of discussions about the pros/cons of adding this sort of thing in the past.

**Comment by mathemancer** [comment]
UPDATE:

I ended up changing the logic so that rather than specifically inferring an empty column to be of type `TEXT`, we instead infer it to be of whatever type it was when input to the inference function.
