### ISSUE TITLE
Bad performances when opening a table containing 100 columns

### ISSUE THREAD

**Issue by frafra** [centerofci/mathesar#2684]
## Description
I imported a CSV file with ~600 records and ~100 columns.
Mathesar needs ~15 seconds to open the table, and a similar amount of time to scroll down to a different position.
I run Mathesar on a server, with 8 dedicated threads of an Intel Xeon Gold 6226R and 64 GB of RAM, so I exclude the hardware could be a problem.

## Expected behavior
Few seconds to load a table and reactive scrolling.

## To Reproduce
It should be enough to upload 600 rows with 100 columns of mixed types.

## Environment
 - OS:: Ubuntu 20.04
 - Browser: Firefox
 - Browser Version: 109
 - Other info: run in Docker containers (dev profile)

## Additional context
It looks there are two different issues: Mathesar slow load of the table in the first place (I see node using the whole available CPU, then Python), and then the browser

**Comment by dmos62** [comment]
Thanks for the report. I'm not sure I understand if it's the backend or the frontend that's bottlenecking in your case. If you could provide some information about that, that would be helpful. And, I'm presuming that we're only talking about the performance once the table is already imported (and you're looking at the table via a URL like `/1/tables/2`), not the import process itself.

**Comment by silentninja** [comment]
> a similar amount of time to scroll down to a different position

@frafra your description seems to be similar to #1499. Can you check the video attached to #1499 and see if it matches with your scenario.


> Mathesar needs ~15 seconds to open the table

Mathesar's backend isn't really optimised to handle more than 20 columns.  Since we rely on an external library for querying database objects like columns, there are a lot of irrelevant queries made when calling certain endpoints like fetching columns. We are aware of the problem and had a [discussion](https://wiki.mathesar.org/en/meeting-notes/2023-03/2023-03-08-removing-sqlachemy-meeting) related to fixing it. Improving performance is our topmost priority but I am afraid it is not a quick fix and might take quite some time

**Comment by silentninja** [comment]
I am marking this issue as a draft until we get a confirmation from @frafra that the issue mentioned here is not similar to #1499 and #1765

**Comment by kgodey** [comment]
I put https://github.com/centerofci/mathesar/issues/1499 and https://github.com/centerofci/mathesar/issues/1765 into the milestone for an upcoming so we can prioritize looking into them.
