### ISSUE TITLE
Internal server error when importing CSVs with long names

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2714]
Follow the same steps as reported in #2634 and observer the error from the screenshot below: 

API: `http://localhost/api/db/v0/tables/12/records/?limit=500&offset=0`

<img width="1512" alt="Screenshot 2023-03-20 at 5 29 52 AM" src="https://user-images.githubusercontent.com/11032856/226218521-75355de8-eee0-4b5e-9a9c-47aa3ff67da2.png">

**Comment by mathemancer** [comment]
This is quite strange. Something somewhere in the call stack has logic to truncate strings to 59 characters max. I have no idea where it's happening, and it's not the database or SQLAlchemy's default reading of the columns of a table.

I suggest we limit column widths to at most 48 bytes (which will always be at most 48 characters) for the moment. I suspect this is (yet another) thing that will be fixed when we simplify things by removing SQLAlchemy. Or at least it'll be easier to figure out where the string is being mangled.

Our tests didn't catch it, since they were checking that strings were being stored correctly (which they are), and then the column names were correct when asking for columns specifically (they are). What's not working is (somehow) a piece of the machinery that gets records of a table, and associates each record with the column names from the table.

**Comment by pavish** [comment]
@mathemancer I assume that might take considerable time. I'm moving this issue out of the `0.1.1` milestone to `0.1.2`.

**Comment by pavish** [comment]
@dmos62 Since Brent isn't available for a while, could you take a look at this?

**Comment by dmos62** [comment]
I'd like to get #2725 merged (it still needs some final touches though), because that will fix the CSV import edge-case. It's currently assigned to Mukesh, but I expect to take it over. I'll follow it up by opening an issue to track the resulting 48-63 discrepancy when importing CSVs (which doesn't seem particularly urgent).

Then, the remaining edge-case is long identifiers on preexisting databases that Mathesar connects to. We have a valid concern that that could trip Mathesar up, but it's also unproven. So, I'll devise a test case for that, and we'll continue from there.

## Tasks

- [ ] #2725 
- [ ] Open an issue to track the resulting 48-63 discrepancy when importing CSVs
- [ ] PR with test case for long identifiers in preexisting database that Mathesar connects to

@silentninja @pavish tell me if this doesn't make sense.
