### ISSUE TITLE
Update `docker-compose` to `docker compose` in documentation

### ISSUE THREAD

**Issue by smruthi49** [centerofci/mathesar#2726]
## Description

using 
```
docker-compose --profile dev up
```
doesn't work.
using 
```
docker compose --profile dev up
```
Works

## Expected behavior

I expected it to set up and give the localhost link for me to access mathesar locally

## To Reproduce

```
cp .env.example .env
```
use this after
```
docker-compose --profile dev up
```
during set up

## Environment
 - OS: Ubuntu 
 - Browser: Firefox

## Additional context

![image](https://user-images.githubusercontent.com/94833021/226377723-c6d6192f-52db-4a0f-b8d4-5c8118919c40.png)

**Comment by pavish** [comment]
@rajatvijay Should we consider this as `user reported` since this came from a contributor/GSoC applicant?

I assumed the label was only for external users of Mathesar. cc: @kgodey

**Comment by kgodey** [comment]
We should not consider this `user reported`

**Comment by Anish9901** [comment]
`docker-compose` is a standalone implementation of the compose tool whereas `compose` in `docker compose` is a plugin for the Docker CLI. The support for `docker-compose` will be dropped from June 2023 since it uses Compose V1, whereas the compose plugin uses Compose V2. If someone wants to use the standalone version the install instructions are provided [here](https://docs.docker.com/compose/install/other/).

**Comment by rajatvijay** [comment]
@Anish9901 does this mean that we should not update our documentation since the support is being dropped by Docker itself?

**Comment by silentninja** [comment]
> @Anish9901 does this mean that we should not update our documentation since the support is being dropped by Docker itself?

We should be updating our documentation to use `docker compose` which is what the issue is for

**Comment by SafeEHA** [comment]
Hello @rajatvijay please i would like to work on this, I see it hasn't been resolved yet and believe this might affect other candidates trying to make installations
