### ISSUE TITLE
Text caret sometimes scrolled out of view when typing into FormattedInput on Chrome

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2758]
## Description
* Edit a number cell, type in a large value
* Notice that the value gets updated and once the length exceeds what's visible on the screen, the cursor is not visible and further updates are not shown.
* The entered value does get updated but it's not visible until the user exits edit mode and enters edit mode again.

https://user-images.githubusercontent.com/11850603/228086282-d1b716e8-ff6f-434d-b27d-69a13bc52851.mov

## Expected behavior
* The cursor should always be visible and newly entered values should be shown.

I remember this was working as expected when the feature was implemented. This is a possible regression which was introduced later, but before we released.

**Comment by seancolsen** [comment]
@pavish this piqued my interest so I did a little investigating. 

- I'm able to reproduce this bug with Chrome (Chromium 111.0.5563.110)

- I'm not able to reproduce it in Firefox or Safari

- Here's a reproduction scenario that's more minimal and easier to inspect:

    1. Merge this code into a simple page like `DatabasePage.svelte`

        ```svelte
        <script lang="ts">
          import { FormattedInput } from '@mathesar-component-library';

          const formatter = {
            format: (v: string) => v,
            parse: (value: string) => ({ value, intermediateDisplay: value }),
          };
        </script>

        <FormattedInput {formatter} style="width: 50px;" />
        ```

    1. Type into the input and observe the bug as described

- I'm able to reproduce it with `FormattedInput` but not with `TextInput`.

- This bug is related to the way that `FormattedInput` works....

    It [handles](https://github.com/centerofci/mathesar/blob/67aaef089f0eaf0bd6745978792856bb7cee4bc9/mathesar_ui/src/component-library/formatted-input/FormattedInput.svelte#L84) the `beforeinput` event, preventing default so that the user never actually "types into the input". Instead, we intercept the key presses before they ever reach the input. Then we use `getOutcomeOfBeforeInputEvent` to see what the text _would have become_ if we had let them type freely into the input. Then we run that text (`userInput`) through the parser. Then we set the value of the input to the `intermediateDisplay` that the parser produced. Finally, we manually set the cursor position.

    With all this imperative logic, it's not surprising there is a bug here. This formatted input stuff is quite complex!

    What seems to be happening is that Firefox and Safari are smart enough to scroll the caret into view after we call `element?.setSelectionRange`, but Chrome is not.
    
- None of this code has changed meaningfully in the past year, so my guess is that we've always had this bug but just not noticed it. I suppose it's possible that the behavior of _Chrome_ changed recently, but I'd find that very surprising.

- I tried playing with different strategies to cajole the input into scrolling its cursor into view, but I couldn't find anything easy. I tried calling `focus()` (even though it's already focused). I tried calling `setSelectionRange` twice, in vain.

- Putting some code like this...

    ```js
    if (element) {
      element.scrollLeft = 1000;
    }
    ```

    ...after the `setSelectionRange` _kind of_ works. It works if you're adding text to the end of the contents. But if you have a long string and you put the caret at the _start_ of the string and hit backwards-delete, then we have the reverse of the current problem (albeit a more rare bug, but a bug nonetheless).

- The only thing I can think of is to look at the text length, look at the caret position, look at the input width, look at the scroll width, and then (taking _all_ those things into account), set a value for `scrollLeft` that would seem to bring the caret into view. Ooof. I'm still scratching my head wondering if there is an easier solution.

**Comment by varunmulay22** [comment]
@seancolsen was there a fix provided for this? In the latest release, I could not replicate the above and the cursor remains active as expected until I save the value, thanks

**Comment by seancolsen** [comment]
@varunmulay22 No, this issue is not yet fixed. Make sure you're using Chrome when reproducing. And make sure you follow the steps in the ticket description, watching the video too. If you still cannot reproduce it, I'd be curious to hear what version of Chrome you're using.
