### ISSUE TITLE
Default value can be set for Uniqueness Constrained columns

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2821]
## Description
Currently, it is possible to set a static default value for a column with uniqueness constraint. **This assignment throws no error, but while auto-creating the records, it immediately violates the uniqueness constraint** (maximum one column can be added successfully).

## Expected behavior
Unique columns should not have a static default.

## To Reproduce
- Set ```restrict to unique``` for a column.
- Set a default value for the same.
- Creating record for the 2nd time will throw an error stating **uniqueness constraint has been violated**.

## Environment
- OS: Ubuntu 22.04.1 LTS
 - Browser: Google Chrome
 - Browser Version: 111.0.5563.111 (Official Build) (64-bit)

## Additional context
Here is a screencast that produces the error.

https://user-images.githubusercontent.com/64671908/232665082-60e25e19-4ea4-4b11-a088-e71de3f8cd72.mp4

- Kriti previously addressed this issue [here](https://github.com/centerofci/mathesar/issues/956#issuecomment-1006664366). 
- Also, as Mukesh mentioned [here](https://github.com/centerofci/mathesar/pull/2780#discussion_r1164088727), we don't support setting dynamic default through an API. So, **the default value block should not be rendered for unique columns**.

So, the solution might be:
1. Not rendering the default value block, when the column is restrict to unique (like ID column).
2. Restict the ```PATCH``` request such that it can't set a default of the same.

**Comment by Aritra8438** [comment]
@kgodey, @silentninja, I have raised the issue, please take a look.

**Comment by rajatvijay** [comment]
LGTM @Aritra8438 go ahead.

**Comment by kgodey** [comment]
Thanks for reporting this, @Aritra8438

**Comment by mathemancer** [comment]
As noted on the PR:

I think implementing this is a bad idea. In the linked PR, I noted a couple of cases where you'd _want_ to set a uniqueness constraint on a column with a static default. It allows certain checks that aren't possible with just a uniqueness constraint (since nulls aren't controlled by uniqueness constraints). I further note that this is the behavior of PostgreSQL, and I think it's much better to gracefully handle the any violations (we already do this for unique constraint violations) and help the user understand what's going on than artificially limit their options.

**Comment by seancolsen** [comment]
My interpretation of the above comment by @mathemancer is that we no longer want to pursue this issue. As such, I'm closing. We can re-open this if we can get some clarity on a new scope for this ticket.
