### ISSUE TITLE
Frontend component actions: Popper, Portal, ClickOffBounds

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#289]
These actions are currently present. However, we still need to handle:
* Unit tests
* Documentation

**Comment by seancolsen** [comment]
I'm closing this because it's been open for almost a year. All that's left here is tests and docs. While additional test/doc coverage would be nice for this component, I don't see it being a priority. We have plenty of front end code without test coverage or docs, and this code doesn't strike me as any more important than other areas of our codebase where we could seek those improvements.
