### ISSUE TITLE
Allow different JSON structures to be imported as tables

### ISSUE THREAD

**Issue by IamEzio** [centerofci/mathesar#2943]
## Problem

Currently our JSON file importing feature does not handle cases when the data is structured in following forms:
- Data is structured column-wise rather than row-wise. Here is an example:
```
{
 "name": ["John", "Jane", "Bob"],
 "age": [25, 30, 40],
 "city": ["New York", "Chicago", "San Francisco"]
}

```
&emsp; &emsp; Our importing feature will create a single row for the above data, with each record being a JSON list.

- Data is structured as an Array of arrays. Here is an example:
```
[
 ["name", "age", "city"],
 ["John", 25, "New York"],
 ["Jane", 30, "Chicago"],
 ["Bob", 40, "San Francisco"]
]

```
&emsp; &emsp; This format is the closest a JSON file can look like a CSV file. Our importing feature will create a single row with each record being a JSON list.

## Proposed solution

Our JSON importing feature should handle these edge cases.

## Additional context

Meta ticket: #2895

**Comment by dmos62** [comment]
For some context, we decided to not pursue this at this time (and just track it instead), because _a)_ handling these cases would require considerably more effort than handling the rest (they're not covered by [pandas.json_normalize](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html), which we're using to normalize JSON), and _b)_ these cases are somewhat rare, which could be part of why Pandas doesn't support them.

I suggest we revist this issue only when we discover that someone needs it.

**Comment by seancolsen** [comment]
I'm closing because I don't think this feature is worth tracking. If a user requests this we can consider it at that point.
