### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#2961]
## Description
This cannot work on Windows because of the pglast dependency. Unfortunately it seems that this is an issue of the libpg_query library and probably will never be fixed: https://github.com/pganalyze/libpg_query/issues/44

## Expected behavior
To be able to install the dependencies on windows

## To Reproduce
Try to instal requirements on windows

## Environment
Windows 10, python 3.9.

## Additional context
If I remove the pglast dependency `pip install -r requirements-dev.txt` works fine. I believe that this can be resolved by removing pglast *completely* since it's used only once. I'd be happy to discuss this more.

**Comment by mathemancer** [comment]
The good news is that we're currently moving the logic that necessitated `pglast` down into the database, and so this requirement will be obsolete in the near future.

**Comment by spapas** [comment]
Hello friends, do we have any news for this issue? I think it would be very useful if we removed that `pglast` dependency so people could run this under windows (I know I want to because I prefer windows for developing, now I need to ssh to a unix machine to run mathesar).

Thank you

**Comment by mathemancer** [comment]
Update for you @spapas : We're still working on moving logic down to the database. Unfortunately, the logic requiring the use of `pglast` isn't yet moved out of python. I'll look at what it would take to do that sooner rather than later, since we expect to do it at some point regardless.

A quick inspection of the relevant code makes it look like we'd just need one (admittedly technical) function in the database to make it happen.

**Comment by spapas** [comment]
Thank you for the update @mathemancer !

**Comment by spapas** [comment]
@mathemancer I'm happy to report that mathesar runs on my windows machine (without docker) !

**Comment by kgodey** [comment]
Thanks for confirming, @spapas!
