### ISSUE TITLE
Remove token-based authentication

### ISSUE THREAD

**Issue by varshadr** [centerofci/mathesar#2997]
## Problem
The Mathesar currently uses cookie-based authentication (cookieAuth) and not token-based authentication (tokenAuth). 
The current OpenAPI specification generated by the DRF Spectacular library includes a security schema called tokenAuth  too, along with cookieAuth.Instead, it should rely on cookie-based authentication using the sessionid cookie only.

## Proposed solution
The **DEFAULT_AUTHENTICATION_CLASSES** setting in the DRF configuration is responsible for the tokenAuth and cookieAuth mentioned in the security section of the API specification file.
The _TokenAuthentication_ class should be removed to fix the problem.

## Additional context
Check for the discussion  [here](https://github.com/centerofci/mathesar/pull/2971#discussion_r1247635663)

**Comment by silentninja** [comment]
I couldn't find any usage of token-based authentication used for our accessing our APIs. Can a frontend developer take a look and confirm if we can remove Token authentication? cc @pavish @rajatvijay @seancolsen

**Comment by pavish** [comment]
@silentninja @varshadr I remember this was added by @Anish9901 to provide a 401 for API endpoints are accessed by unauthenticated users. @silentninja I remember you reviewed the PR and was involved in the discussions.

I don't remember why TokenAuthentication was required for it, and I'm okay with it being removed since we don't really have any token auth yet.

However, please ensure it doesn't break the current functionality i.e. unauthenticated API requests should return 401, while unauthenticated routes (page views) should return a 404.

Refer related PRs and discussion: https://github.com/centerofci/mathesar/pull/2460

**Comment by silentninja** [comment]
Thanks @pavish I completely forgot about that and didn't check the commit logs.

**Comment by silentninja** [comment]
@varshadr Sorry for not catching this earlier. I will close this issue and the relevant PR as we need the Token Authentication even though we are not using it on the front end.

**Comment by varshadr** [comment]
@silentninja Oh, okay!

**Comment by pavish** [comment]
Closing issue as mentioned above: https://github.com/centerofci/mathesar/issues/2997#issuecomment-1643976083
