### ISSUE TITLE
Support for `Peak day of week` aggregation function while summarizing columns

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#3003]
## Problem
We need to create an aggregate function for `Day of Week` which imitates `average`, the only difference will be it will take modular mathematics into consieration.

## Proposed solution
It would be nice to support such an aggregate as a transformation step while summarizing Date and DateTime columns.

## To Discuss
- `Peak day of week` aggregation function should only be available for columns with **Date** and **DateTime** data type.

## Additional context
This feature request is a part of GSoC '23 project, [Add More Summarization Functions](https://summerofcode.withgoogle.com/programs/2023/projects/D9XvkQCN).

**Comment by seancolsen** [comment]
I'm closing this because my understanding is that we decided not to pursue this feature. In particular, this feature would be technically challenging to implement in a manner consistent with our intent to translate the Mathesar UI into several languages.

If I'm wrong or misremembering, we can re-open.
