### ISSUE TITLE
Error when imported data file has null or duplicate `id` value

### ISSUE THREAD

**Issue by IamEzio** [centerofci/mathesar#3009]
## Description

Currently, if all the entries in the imported datafile lack `id` column, Mathesar creates id column with default ids (1, 2, .. so on). However, if the data entries have an `id` attribute, we use that. However, we don't handle the case where we have null or duplicate id values.

Case when we have `null` id value for a row:

https://github.com/centerofci/mathesar/assets/89375125/8f1af34a-b199-4423-bb26-181844b18472

Case when we have `duplicate` id value for a row:

https://github.com/centerofci/mathesar/assets/89375125/bfbc1f7f-470c-4a10-8a2e-16c0fb022046

## Expected behavior

If we face such a case, the we have following possible fixes:
1. rename id column and let backend generate one,
2. remove objects with duplicate ids and those without ids (notifying the user that this was done would be a hassle),
3. forbid importing with duplicate or missing id values.

## To Reproduce

Try to import a CSV/TSV/JSON file that has an `id` column but has `null` or `duplicate` value for `id` in one of the rows.
View the video above for more reference.

## Environment
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Browser Version: Version 104.0.5112.79

**Comment by dmos62** [comment]
After a brief discussion, we (me and Anshuman) decided that the 3rd possible fix (forbid importing data with duplicate or missing id values) is the way to go, since it's safe, unsurprising and doesn't require significant UX work.

We also noted that another possible solution that might be worth looking into in the future is to allow the user to choose whether to use the imported `id` column as the PK column or to generate a new one alongside the imported one.
