### ISSUE TITLE
Support unknown Postgres types

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3024]
Mathesar currently (erroniously) presumes that each Postgres data type it sees will be known via the relevant enums ([see comment](https://github.com/centerofci/mathesar/issues/3024#issuecomment-1632812393)) and, when an unknown type is encountered, Mathesar panics ([see bug report](https://github.com/centerofci/mathesar/issues/2709)). We want Mathesar to handle unknown types gracefully.

**Comment by dmos62** [comment]
- We can address this
- Our type system currently presumes that each type encountered will be one of [`PostgresType`](https://github.com/centerofci/mathesar/blob/5156cd967cd9e3fb6e510b7fb26298dbff19fe70/db/types/base.py#L91)s;
- Our type system currently presumes that each `PostgresType` will be one of [`UIType`](https://github.com/centerofci/mathesar/blob/5156cd967cd9e3fb6e510b7fb26298dbff19fe70/mathesar/database/types.py#L13)s
- Long term, it's worth thinking of how users themselves could extend what we know about types
  - E.g. while we can make `citext` not crash Mathesar, someone does need to tell it that it's a text type so that the appropriate filters become applicable to it (other features might depend on this too);
- I'm slightly concerned this will reveal other problems caused by these presumptions and thus become a larger undertaking than initially thought
- The most direct solution that comes to mind is instantiating `PostgresType` instances on-the-fly for unknown types, and putting all unknown `PostgresType`s in the [`UIType.OTHER`](https://github.com/centerofci/mathesar/blob/5156cd967cd9e3fb6e510b7fb26298dbff19fe70/mathesar/database/types.py#L123) bucket: not sure how feasible this is.

This would be a notable improvement. @seancolsen good job thinking of this.

I'm considering attempting to do this either instead of the new type issues or in compliment to them.
