### ISSUE TITLE
Why both psycopg-binary and psycopg2-binary ?

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#3110]
## Description
The requirements.txt file of this project https://github.com/centerofci/mathesar/blob/develop/requirements.txt includes *both* psycopg-binary==3.1.8 and psycopg2-binary==2.8.6. Why ? 

Also please notice that psycopg2-binary==2.8.6 is very old (~ 3 years old) and should definitely be replaced by psycopg2-binary==2.9.6, see the psycopg2 binary release page on pypi: https://pypi.org/project/psycopg2/#history

## Expected behavior
To *not* require both psycopg2 and 3. Or at least to use a current version of psycopg2-binary.

## To Reproduce
Not needed.

## Environment
Not needed.

## Additional context
Unless I'm missing something I'd propose to drop psycopg2 completely and stick with psycopg3.

**Comment by mathemancer** [comment]
Hi, @spapas . We're aware of this, but thank you for reporting that it has you concerned, since that helps us prioritize our work.

The situation is that we are using SQLAlchemy 1.4, which requires `psycopg2`. However, we're on the road to removing SQLAlchemy from our codebase. While SQLAlchemy is a great package, we're now finding that it solves a bunch of problems we don't have, and doesn't solve some of the problems we do have.

As part of the removal, we're using `psycopg` (i.e., 3) for making queries to the database wherever we've removed SQLAlchemy. Further, we're avoiding updating SQLAlchemy to 2.0, since we don't want to put work into migrating when we're planning to remove the package anyway. So, the long-term is exactly what you suggest, i.e., to only require `psycopg` 3. 

Regardless, I'll experiment with updating `psycopg2` to a more modern version, since I think that will be relatively simple.

**Comment by dmos62** [comment]
@spapas I derived a new issue from this: #3148. Do you think it captures all the action items left in this issue, and thus this issue can be closed?

**Comment by spapas** [comment]
@dmos62 yes let's close this in favour of #3148. Using the latest version of psycopg2 is good enough!
