### ISSUE TITLE
Insert broken when there's not primary key

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#3246]
## Description

When a table does not have a primary key, attempting to use the UI to create a new record results in the backend throwing an unhandled 500 error.

## Expected behavior

When a `POST` request representing a new empty record is sent for a table with no primary key, the server should respond with a 405 error, since we can't allow creating (or editing) rows on tables with no primary key. The error should be associated with some informational `APIException` stating that you can't insert into tables without a primary key.

The implementer should add an API test to validate their solution.

## To Reproduce

1. Using psql or some other client, create a table without a primary key.
2. In the UI, navigate to that table.
3. Click the `+` to add a record. 
![image](https://github.com/centerofci/mathesar/assets/6829750/897e36a2-4b39-4d1a-a87d-83ad0ca1d169)
4. Observe the 500 response.
5. See the error (via mouse-over) in the UI: 
![image](https://github.com/centerofci/mathesar/assets/6829750/95dcb4d1-bc7e-4633-aff4-35d6e3c3e972)
6. See the `tuple index out of range` error in the devtools.

**Comment by piyushupadhyay19** [comment]
Hey, I observed that the Mathesar web interface displays 'mathesar_tables' as a database. However, I couldn't connect to mathesar_tables database. I successfully connected to 'mathesar_django' database and made a table there using psql but I cannot find that table in UI because I think table needs to be created in mathesar_tables database and not mathesar_django database? Can you please clarify if 'mathesar_tables' is an alias for another database specified in my project's configuration, or if there's a different method to access it?
