### ISSUE TITLE
Handle `NUMERIC` data type in the backend.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#377]
This issue is to ensure that Mathesar can handle the Postgres `NUMERIC` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `NUMERIC` if it's possible to do so.
- Users can set and change the `precision` and `scale` of a given `NUMERIC` column via a `type_options` field in the API.
- Automatic type inference during file import suggests `NUMERIC` when it makes sense to do so. 

**Additional Context** 
- See PR #368 for code that calculates which types are allowed for a column.

**Comment by kgodey** [comment]
Please note that some of the implementation for this task is already done.

**Comment by sp35** [comment]
Hi, I'll try working on this.

**Comment by kgodey** [comment]
Sounds good @sp35, assigned.

**Comment by sp35** [comment]
Hi, I'm unable to work on this issue at the moment, so a heads up (to be confirmed) in case someone would like to work on this:

> * Users can use the API to change a column to `NUMERIC` if it's possible to do so.
>
This is possible via a `PATCH` request as of now. We just need to catch the exception and raise a validation error, if it fails.

> * Users can set and change the `precision` and `scale` of a given `NUMERIC` column via the API.
>
Since we shouldn't add such additional fields to `ColumnSerializer`, we can add a single field  `config` which would be a `rfs.JSONField`.

> * Automatic type inference during file import suggests `NUMERIC` when it makes sense to do so.
>
This should remain a concern when we add other number data types. As of now, numeric in string format is suggested as `NUMERIC` which is correct.

**Comment by kgodey** [comment]
@sp35 Thanks for investigating the issue.
