### ISSUE TITLE
Handle `SMALLINT` data type in the backend.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#378]
This issue is to ensure that Mathesar can handle the Postgres `SMALLINT` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `SMALLINT` if it's possible to do so.
- Automatic type inference during file import suggests `SMALLINT` when it makes sense to do so. 
  - I'm not sure this actually ever makes sense, I think we should default to `INTEGER` when we detect integers, but I'm open to differing opinions on when this might make sense.

**Additional Context** 
- See PR #368 for code that calculates which types are allowed for a column.

**Comment by mathemancer** [comment]
> * Users can use the API to change a column to `SMALLINT` if it's possible to do so.
> * Automatic type inference during file import suggests `SMALLINT` when it makes sense to do so.
>   
>   * I'm not sure this actually ever makes sense, I think we should default to `INTEGER` when we detect integers, but I'm open to differing opinions on when this might make sense.

I also don't think we should suggest `SMALLINT`.  A novice user might not understand the implications, and the savings aren't really worth the potential confusion, especially since sometimes the decision about what type to use might be made with a small amount of data.  If the user knows what they're doing, and wants  to use it, they can always change.
