### ISSUE TITLE
Spec for implementing display options for Columns

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#392]
## Problem

We'll need to implement display options for columns in the service layer. Since we don't currently have a `Column` object in the Django layer, it's unclear how we should be doing this.

## Proposed solution

We need a spec for how to implement this, and then we need to implement it. This issue is just for the spec; implementation will be covered in the various backend issues for individual data types.

**Comment by kgodey** [comment]
The spec I'm proposing for storing display options is pretty simple:
- Create a `Column` Django model with a `display_options` JSON field to store display options.
  - Update `/api/v0/columns/` to use the Django model.
  - Implement automatic DB reflection of columns.
- Set up allowed display options for each Mathesar type somewhere in the code and validate them when creating a column.
- While reflecting columns from the database:
  - if we see a column at the same index with the same data type but the name is different, we'll update the existing Column object and retain the display options.
  - if we see fewer columns than we expect from previous reflection, we'll use the names of the columns to figure out which ones have been deleted and only delete those. We'll also double check the types to make certain.

This means that when a table's columns are deleted or renamed outside of Mathesar, we might lose some display options. This seems unavoidable. I investigated the idea of storing display options in Postgres column comments, but columns are identified by the table's `OID` and column index, which is what we'd be storing anyway. This way, we don't have to touch the database (people may already be using column comments for other things).

**Comment by kgodey** [comment]
@mathemancer I'm going to move this to "Needs discussion", let me know what you think. If that approach looks good, I'll create/update tickets for implementation.

**Comment by mathemancer** [comment]
I think this makes sense.  As long as it's only display options in the models (and those should be easy for the user to redo if necessary), I think it's okay that we can't guarantee we won't lose them if the table is significantly changed by another client.

I still think it would be wise to avoid giving an "id" that's used by the API for each client.  The reason is that this will actually _create_ confusion since it can't reliably be made to refer to the same actual column at the DB level.

**Comment by kgodey** [comment]
> I still think it would be wise to avoid giving an "id" that's used by the API for each client. The reason is that this will actually create confusion since it can't reliably be made to refer to the same actual column at the DB level.

@mathemancer Could you elaborate on the issues you see with this?

**Comment by mathemancer** [comment]
> @mathemancer Could you elaborate on the issues you see with this?

Unfortunately, a column isn't a stable entity of its own in the DB, as we've discussed before.  There's no way to detect whether (for example) a column was deleted or renamed by reflecting the DB.  If we give an `id` number to the column with (for example) a given name / index combo, we'll be implying a stability and identity that doesn't actually exist.  An example of where this could create serious problems would be when deleting more than one column.  For columns that have identities, it shouldn't matter what order they're deleted in, since the ID numbers for other columns aren't affected by deleting a given column.  However, if we're using something like name, index to _identify_ columns, the ID cache will be broken for any column to the right of one just deleted, since whenever we delete columns, the indices of columns to the right change, screwing up the ability to accurately identify the column we want.  This problem isn't actually solved by using "index" instead of some "id" for a column, but it makes it obvious that the number of the column _isn't_ an id, and shouldn't be treated that way.  I think it would be better to be "honest" in the API that there isn't a stable identifier for columns, so that clients can act accordingly.

Please let me know if this still isn't convincing.

**Comment by kgodey** [comment]
@pavish I remember you had an argument for why columns should have IDs, but I can't remember what it was. Can you review @mathemancer's comments and let me know what you think? If you still think columns should have IDs, please explain your reasoning.

@mathemancer I'll review @pavish's reasoning before responding.

**Comment by pavish** [comment]
@kgodey @mathemancer 

>  This problem isn't actually solved by using "index" instead of some "id" for a column, but it makes it obvious that the number of the column isn't an id, and shouldn't be treated that way. I think it would be better to be "honest" in the API that there isn't a stable identifier for columns, so that clients can act accordingly.

The client cannot make use of index to perform any reliable user action on columns. Here's a scenario on top of my head. There may be more serious effects. I can put more thought into this.

Let's assume that we have two clients that work on the same table:

* Client A deletes a column, causing a shift in index
* Client B tries to update any other column, after the deleted column.

This _will successfully update_ a different column than the one that was intended by the user, and there will be no way to get the message across to the user.

Problems with concurrent usage can be expected until a change detection mechanism is in place. However even without it being implemented, for other db objects we can rely on the results of user operations.

* If two clients update the same cell in a row, the user will always know that the row that got updated was the one that they intended to update.
* But when two users try to update the same column, they cannot reliably know if they updated the column they intended to update.

**Using the column name instead of index is more reliable.**

For delete, using the name would work fine. For rename: If one user renamed the column, it will result in an error if a different user is trying to update it again. This is okay. We prevent doing any operation on the db that might result in an undesirable state.

But if we use index, if one user deleted a column, and a different user tried to update the same column/any column after it, it may show a successful update message to the user, but internally it would have updated a different column. This is not okay. 

I think using index is a bad idea in any level both directly or by creating an id with index + name. Using the name as the identifier is a much better and reliable option.

**Comment by kgodey** [comment]
The issue with having a name as an identifier is that names need to be properly quoted if they have double quotes or things like that.

I think it would be best to modify my spec above to have an `id` that's based on the name and index. If either changes, we destroy the Column object and create a new one with a new `id` (we never update Column objects). We can copy display options over to the new object based on the same rules as my original spec.

I think this solves a bunch of issues:
- Columns will have unique identifiers
- Concurrent updates of the same column will fail because they will have different IDs
- We don't show a false sense of stability for columns because the IDs will change, so it's clear that they are not the same object.

**Comment by pavish** [comment]
This does pose one concern with optimization. If a column gets deleted, the index of all the columns after it will change. This will result in destroying all those Column objects and recreating them.

Autogenerating an id based on only the column name could be more advantageous.

One can argue that we may have race conditions if we only use the name to generate id, eg., if the user switches the names of two columns. However, similar cases would apply when we use (name + index) as well.

**Comment by kgodey** [comment]
I think @mathemancer's concern about a false sense of stability would apply if we just used the name; a column with a different index but the same name just isn't the same column in the DB and shouldn't have the same `id`. 

If we run into optimization concerns down the line, we can update the implementation, but it seems like premature optimization to focus on it now in lieu of representing the DB objects accurately.

**Comment by pavish** [comment]
@kgodey Makes sense.

**Comment by mathemancer** [comment]
> I think it would be best to modify my spec above to have an autogenerated `id` for columns similar to other database object. If name or index of the column changes, we destroy the Column object and create a new one with a new `id` (we never update Column objects). We can copy display options over to the new object based on the same rules as my original spec.

 I can get behind this.

After thinking about @pavish 's comment a bit, I think he has some good points about referring to columns by name, not index.  Perhaps I was trying too hard to have a number to pass back and forth without generating one. 
 To put a point on it, for modifying or deleting a _column_ in actual SQL, you need to know the column's name, but not its index (in fact there's no syntax to refer to a column by index when updating).  For inserting or updating _rows_, it's possible to give the information without knowing the columns' names if desired (so in that case you'd be implicitly refer to the columns indices to order the inputs).

Even so, I like the idea of requiring both to be what's expected (for safety's sake) for updates of columns at the moment.

**Comment by kgodey** [comment]
I'll go ahead with the implementation I suggested. Thanks!

**Comment by kgodey** [comment]
The following issues will be updated to implement this issue:
- #658 
- #390 
- #433
- #386 
- #428 

I'll also create more for any other types with display options.

**Comment by silentninja** [comment]
@kgodey Are display options frontend settings, as in are they used by the frontend to format the data or does the backend need to send formatted data based on the display options. I can see valid use cases for both options.

For example, in the case of a boolean type label or a date format, the use case would be to set a default representation of the value when it gets out of the database either through the api or through the UI. On the other hand, can be used as just a display setting just like a sort. 

Based on the naming of the field, I am guessing it's meant for the latter use case

**Comment by kgodey** [comment]
@silentninja They are used by the frontend to format the data. The backend should avoid taking responsibility for presentational aspects as much as we can since the API is designed to support building new clients.

Please see [this design spec](https://wiki.mathesar.org/design/specs/global-data-type-components) for what we plan to use the display options for. We'll be using it for anything under "Display" in the `Data Type Options Menu Prototype` Figma link.
