### ISSUE TITLE
Default primary key column should be `id`

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#394]
## Problem

Currently, our default primary key column is called `mathesar_id`. I think it would be cleaner to create a column named `id` since the `id` is not related to Mathesar's operations in any way.

## Proposed solution

We should rename the `mathesar_id` column name to be `id`.

As part of this, we should also check for a column named `id` when importing data files and either rename that column or repurpose it to be the primary key field. It's cleaner to use an existing field if there is one, and we also want to avoid a column name collision.

**Comment by mathemancer** [comment]
The original thinking behind `mathesar_id` was specifically to avoid collisions with (reasonable) user column names.  Overall, I agree that it's cleaner to use `id` when possible for the primary key column, but we'll need to handle a number of tricky user-communication issues to make it work.

1. What if their `id` column is inappropriate for a primary key?
   My assumption is that we'd try to detect "inappropriate" and then rename their column, and initialize our own `id` column.  Is that what you're thinking?
2. What if the data in an imported `id` is appropriate, but the user doesn't understand the implications of a primary key column and have reason to create a duplicate or `null` entry in that column later?  (Or delete the column, or extract it to its own table, etc.)
   This one has me concerned.  Maybe we should try to portray the implications to the user so they can make a decision at import time?
3. Since their `id` column may be something besides sequential integers, how will we help them generate new (unique) values for the column?  I.e., what if their `id` values are md5s?  I don't think it's necessarily feasible to detect _all_ possible things that could reasonably be used for IDs.
   Maybe an initial solution could be to _only_ accept sequential integers as an `id` column, but that would be kind of weird to detect:  What if they've deleted an entry, and so one is missing?  How many can be missing before 'sequential' stops making sense?

**Comment by kgodey** [comment]
>     1. What if their `id` column is inappropriate for a primary key?
>        My assumption is that we'd try to detect "inappropriate" and then rename their column, and initialize our own `id` column.  Is that what you're thinking?

Yes, that's what I was thinking.

>     2. What if the data in an imported `id` is appropriate, but the user doesn't understand the implications of a primary key column and have reason to create a duplicate or `null` entry in that column later?  (Or delete the column, or extract it to its own table, etc.)
>        This one has me concerned.  Maybe we should try to portray the implications to the user so they can make a decision at import time?

I'm not sure we need to let users know about that at this stage, it seems like an edge case that we could handle after the MVP.  

Generally, creating a separate issue for how we handle primary keys is on my list for today. I'm not sure we should allow them to alter primary keys to their own tables. We should support duplicating columns in our data modeling milestone, so they could always duplicate it into a regular column and do whatever they wanted.

>     3. Since their `id` column may be something besides sequential integers, how will we help them generate new (unique) values for the column?  I.e., what if their `id` values are md5s?  I don't think it's necessarily feasible to detect _all_ possible things that could reasonably be used for IDs.
>        Maybe an initial solution could be to _only_ accept sequential integers as an `id` column, but that would be kind of weird to detect:  What if they've deleted an entry, and so one is missing?  How many can be missing before 'sequential' stops making sense?

I think we should only accept integers (that are unique) for now and treat them as sequential based on the highest number.

**Comment by mathemancer** [comment]
I think that all makes sense for now.

**Comment by kgodey** [comment]
Primary key issues, FYI:
- #439 
- #440 
- #441

**Comment by bohemia420** [comment]
can we adopt the pandas way, they'll always introduce "index" if otherwise forbidden in `read_csv`. We can default to create an index (i.e rn/rownum) but a user should cleverly (maybe exoplicitly) know means to just skip a mathesar id being created and pass/specify unique identifier)?

**Comment by kgodey** [comment]
@bohemia420 I don't understand what you are suggesting. Can you explain in more detail?

**Comment by bohemia420** [comment]
@kgodey just like Panda's `read_csv` e.g `df = pd.read_csv(index_col = 'Column A')`
```
**index_col**: int, str, sequence of int / str, or False, default None
Column(s) to use as the row labels of the DataFrame, either given as string name or column index. If a sequence of int / str is given, a MultiIndex is used. Default "False"
```

should the index_col be missing, just like pandas, do indices `df.index` way.

Technically, it is the same as you suggested, but rather than implicitly trying to infer an `id` column and renaming/repurposing it, can we just ask during upload for uniqueness-PK/composites? 

bereft of these inputs, instead of an extra id / mathesar id, it can be a :

```
select row_number() over(), *
           from   <table>;
```

that is transient as per use. `row_number` is to RDBMSes what `df.index` is to pandas. but are funcs rather than explicit columns. My reservation is users might not always like seeing an id/mathesar column, esp for tables that are mostly mappings (e.g coutry -> currency -> capital city).

**Comment by bohemia420** [comment]
> permanent ID for much of Mathesar's functionality on the frontend
this could be implicit too (e.g props) just that not displayed. Nevertheless I second the thought on not asking users too much, and users can delete it anyway 👍 
thanks for [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration), love it. Anyways feedbacks can bring remediations, always.

**Comment by kgodey** [comment]
> this could be implicit too (e.g props) just that not displayed. 

Another general design decision we've made (although I'm not sure if it's documented anywhere) is that Mathesar doesn't hide the database's details from users. We'd rather educate users about what things mean so that they can learn about various concepts and become advanced users over time (if they choose). If they didn't want to see the ID, we would guide them towards making a view that doesn't include that column.

**Comment by rajeshkumarrs** [comment]
@kgodey ... I will work on this issue. Thanks!

**Comment by kgodey** [comment]
thanks @rajeshkumarrs! assigned.
