### ISSUE TITLE
Design for working with primary keys

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#439]
## Problem

DB primary keys are used for functionality within Mathesar and we need to think through how we display them, use them, allow them to be modified, and so on.

## Proposed solution

We need designs for the following functionality:
- We should show which columns are primary keys to the user (denoting them in some special ways).
- We should disable editing of existing primary key values in records.
- We should show primary key constraints in the Table constraints editor and in the column information.
- We should allow users to remove the primary key constraint for a column. If a column has no primary key, then it loses a lot of functionality and we need to warn the users about that.
  - More detail in #396
- If a user is viewing a table without a primary key or with multi-column primary keys, we should show an informational message that tells users that some features are disabled because they have no primary key or a multi-column primary key.
  - If there is no primary key, we should show the user buttons that allow them to add a primary key field with one click or convert an existing field into a primary key field.

## Additional context

- #395 
- #396
- [Postgres docs on primary keys](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS)
- https://github.com/centerofci/mathesar/issues/1245

**Comment by pavish** [comment]
I believe all items in this ticket is already handled, except:

If a user is viewing a table without a primary key or with multi-column primary keys, we should show an informational message that tells users that some features are disabled because they have no primary key or a multi-column primary key.
If there is no primary key, we should show the user buttons that allow them to add a primary key field with one click or convert an existing field into a primary key field.

I'm closing this issue and opening a separate one for that: https://github.com/centerofci/mathesar/issues/2685.

**Comment by kgodey** [comment]
I don't think we let people add and remove PKs in the constraints modal, which was also part of this ticket.

**Comment by pavish** [comment]
> I don't think we let people add and remove PKs in the constraints modal, which was also part of this ticket.

Thanks for the catch, it's tracked here: https://github.com/centerofci/mathesar/issues/2686
