### ISSUE TITLE
Table API should support creating tables without names

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#449]
## Problem

We shouldn't require a name while creating a table via API.

## Proposed solution

If there's no name provided, we should auto-generate one according to some pattern.

## Additional context

Please post the pattern you plan to use to generate names on this issue and get feedback from @kgodey and @mathemancer.

**Comment by eito-fis** [comment]
If we don't care about human readability, python's `uuid.uuid4` seems like it would do the job.

If we do care about readability, a decent general solution might be to just name it something like `New Table n`, where `n` starts as `len(Tables.objects.all())` and increments until we find an unused name. Another solution specific to tables generated from data files is to use the data file name, since that's already guaranteed to be unique by Django. 

I think my preference is to do `New Table n` for everything to remain consistent, but I could also see using data file names when we have then (or just using uuid for everything).

**Comment by kgodey** [comment]
We do care about readability, since it shows up in UIs. I like using data file names when we have them and `Table n` when we don't (I don't think we need the `New`, since it'll show up on the UI, brevity is better).

**Comment by mathemancer** [comment]
@eito-fis Django doesn't guarantee uniqueness of table names from data file names.  The user could have tables that _aren't_ from data files that have a similar name (especially for common names like "data").
