### ISSUE TITLE
API for reading views

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#467]
## Problem
Users will want to look at their database views.

## Proposed solution
We should create a read API for views at `/api/v0/views/` that offers both list and detail views, similar to tables. This will probably involve creating a `View` Django model.

The View API should return, at least:
- The view's ID
- The view's name
- The schema the view is contained in
- Details about the view's columns
  - If possible, the view should return data about where the columns are pulled from (the source table/view)
- The query that generated the view 

Views should also have sub-APIs for `records` and `columns`, just like tables.

## Additional context
- #466
- Please spec out this API before implementation and get feedback from @kgodey and @mathemancer.
- The API should indicate whether this view is editable. Please see:
  - #468
  - #464
  - #465  
- Mathesar's [API Standards](https://wiki.mathesar.org/en/engineering/architecture/api-standards)

**Comment by mathemancer** [comment]
Since there will be so much overlap between a `View` model and the current `Table` model, the implementer should consider abstracting common functionality out to a `TableLike` model (maybe with a better name).  Many of the underlying functions called for reflecting, getting records, listing columns, etc. should work for both views and tables without modification (though this needs to be verified of course).

**Comment by kgodey** [comment]
I'm closing this issue. Backend work will be tracked in these issues once design work has been completed:
- #455 
- #466
