### ISSUE TITLE
New CSV imports use autogenerated column names.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#491]
## Description

According to #459, newly imported CSVs are supposed to use the first row as headers by default. However, newly uploaded CSVs are showing autogenerated column names.

## Expected behavior

The first row of the CSV should be used as header names by default.

## To Reproduce

Upload a CSV from the Mathesar UI. Column names will be of the form `column_0`, etc.

**Comment by obulat** [comment]
I would like to submit a PR for this issue.

The problem is that when receiving HTML-encoded data, Django treats any omitted Boolean fields as `False`. This means that the `DataFile` model's `header` field is set to `False`, instead of the default value of `True`. [Here is a link DRF's documentation describing this behavior of the Boolean fields](https://www.django-rest-framework.org/api-guide/fields/#booleanfield).

This problem can be solved by changing the `DataFileSerializer`:
```
    class Meta:
        model = DataFile
        fields = [
            --remove 'header'--
        ]
        extra_kwargs = {...
                        'header': {'required': True},}
                        ```

**Comment by kgodey** [comment]
@obulat Hey Olga! Please go ahead and submit a PR, I've assigned the issue to you. I didn't know that about DRF and boolean fields, thanks for the explanation.

**Comment by obulat** [comment]
Hi @kgodey 😄 I didn't know that either, it took some debugging to find out.

**Comment by mathemancer** [comment]
Ah, I forgot to check with defaults!

**Comment by kgodey** [comment]
@obulat The issue is still happening even after your PR was merged (try uploading a CSV using the UI, observe that column names are `column_0`, etc. and the first row is treated as data)

**Comment by obulat** [comment]
Oh no. I probably broke something while trying to fix tests, let me see what happened
