### ISSUE TITLE
TypeScript problem in TableView component

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#757]
In `src/sections/table-view/TableView.svelte` the line reading

```ts
await deleteTable(activeTab.id);
```

has the following problem:

> Argument of type 'unknown' is not assignable to parameter of type 'number'.ts(2345)

## More details

- This problem makes sense to me, given that `activeTab` is a `MathesarTab`

    ```ts
    export interface MathesarTab extends Tab {
      id: unknown,
      label: string,
    }
    ```

    and `deleteTable()` wants a `number`.

- I don't see any linting errors or build errors related to this problem -- it's just showing up in VS Code.

## Thoughts

- I'm surprised that a TS problem made it through our CI pipeline. The PR was #650. I don't understand enough about our TS setup or our CI setup, but maybe we want to create a separate ticket to address the underlying failure of those systems to catch this problem.

- The code location has some code smell too. It makes me think, _"why am I passing the ID of the __tab__ when I want to delete the __table__?"_ From what I can tell, the ID of the tab _is_ currently the ID of its table. But that connection is not clear to me just from reading the code, which is why I find the code to be smelly. For example if someday we decide to refactor the tabs system to assign auto-incrementing integers as IDs, then we'd have a sneaky bug here.

- I'm not sure of the best fix here, but my intuition is pointing me towards adding a `tableId` field to `MathesarTab` -- or some other way of more explicitly communicating the fact that we're storing the table id within the tab.

    It would be nice to have your input on the best way forward, @pavish.

**Comment by pavish** [comment]
The tab system was refactored as part of https://github.com/centerofci/mathesar/pull/816, which fixes this issue. tabularData is now part of the tab and we do not use tab.id anymore to identify the table.

We have disabled the most problematic eslint rules for now. Typechecking using svelte-typecheck is supposed to be handled in https://github.com/centerofci/mathesar/issues/767.

I'm closing this issue since the problems mentioned here are fixed and it's no longer relevant.
