### ISSUE TITLE
UX to allow user to set value to NULL within a cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#780]
## Problem

There is no way, as far as I can tell, for the user to edit a row and set the value of a particular cell to `NULL`.

## Proposed solution

We need to define the UX for this.

**Comment by pavish** [comment]
@ghislaineguerin Since UX needs to be defined for this issue, I've assigned it to you. Please feel free to post a mockup or provide your thoughts on what would be a good design for this, so that we can move ahead.

After the UX is decided upon, as we discussed in [New issue format discussion #763](https://github.com/centerofci/mathesar/discussions/763), we will work on the frontend with the same issue.

**Comment by kgodey** [comment]
Assigned to myself to make implementation issues.

**Comment by seancolsen** [comment]
Now that we've defined the UX in [NULL Value Specs, scenario 3a](https://wiki.mathesar.org/design/specs/specs-null-values#steps-for-3a), I'm closing this ticket in favor of #930 which is a more specific follow-up based on the spec. I've confirmed that no further back-end work should be needed.
