### ISSUE TITLE
Add examples to let users (and developers) easily tinker

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#82]
**Problem**

Some users (and developers) may want to play around with Mathesar, or experiment with features contained in the `db` package, but not yet available through the UI or API. 

**Proposed solution**

We should add an example Jupyter notebook showing what the `db` package is able to do.
- The notebook should not require Django to be loaded
- The notebook should be able to run outside of Docker.

**Comment by lekhit** [comment]
Hey @mathemancer,
https://colab.research.google.com/drive/12dK2377I5uKqIPIqyPj1OJcJ1VbW-FdM?usp=sharing
please take a look at this.
## Points considered while making this 
- The notebook should not require Django to be loaded
How?
Basically this notebook creates a seperate requirements.txt file for the db repo. Since Django is not necessary to for this part so it is not even installed much less required. 

- The notebook should be able to run outside of Docker.
Almost all the setup part in done in the notebook itself so Docker environment is not nessary

- Bonus
Considering that some users/colab may not have postgresql install. So to facilitate these users, this script even Allows users to get postgresql installed and setup in their system

Tutorial:
To keep the tutorial simple for understanding it 
- Facilitates the basic CRUD app
- Many may find using engine,Schema and such terms quite overwhelming so the tutorial provides a basic usage API implemented with simple functions
- Some basics are explained about the process of installation.

![Screenshot 2023-04-09 at 8 03 43 PM](https://user-images.githubusercontent.com/82832791/230778919-d6b90641-cfaa-4149-b422-99a442779497.png)
