### ISSUE TITLE
Duplicates filter should work with other filters

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#846]
## Problem

- Please see https://github.com/centerofci/mathesar/issues/770#issuecomment-978850882

## Proposed solution

Ideally, the duplicates filter should work with other filters. If this is not simple to do, we may need to reevaluate the UI for it.

## Additional context

- https://github.com/centerofci/mathesar/issues/501#issuecomment-899795976

**Comment by dmos62** [comment]
I ran into this problem when working on the filtering API. At the moment we're trying to expose the duplicates-only filter through the `filters` query parameter, which is awkward (see `db/records/operations/select.py#_validate_nested_ops` and `db/records/operations/select.py#_validate_nested_ops`), because normally that parameter is parsed by `sqlalchemy-filters`, but now we have to parse it as well to verify that this custom filter is well formed.

Can we have the duplicates-only filter as a separate query parameter, whose value is either `None` or a list of columns? The presumption is that the query generated by `db/records/operations/select.py#_create_query_with_duplicate_filter` never conflicts with the SA filters applied via `apply_filters`.

**Comment by pavish** [comment]
> Can we have the duplicates-only filter as a separate query parameter

Inorder to do this, the UX for filters needs to be rethought.

**Comment by kgodey** [comment]
> At the moment we're trying to expose the duplicates-only filter through the `filters` query parameter on the `records` endpoint, which is awkward (see [0] and [1]), because normally that parameter is parsed by `sqlalchemy-filters`, but now we have to parse it as well to verify that this custom filter is well formed.

@dmos62 I think it might make sense for us to move the filtering code into Mathesar's codebase instead of forking `sqlalchemy-filters` and using that fork. Filtering is a core part of our product and it would help us have more control. We won't have this problem then.

Are there any other problems that you foresee with that approach?

**Comment by dmos62** [comment]
@kgodey I like the idea to do filtering on our own! I think we're in a good place to make that refactor.

Only thing is that I'm having trouble defining what the duplicates-only filter is compared to the other filters/predicates we're currently defining. It seems to be in some other class. I'll have to digest this tomorrow.

**Comment by kgodey** [comment]
Okay, thanks! It might make sense to talk to @mathemancer about removing the dependency on `sqlalchemy-filters`, he originally proposed it during a call we had.

**Comment by mathemancer** [comment]
No hard feelings from me at all if we remove `sqlalchemy-filters`.  I just like to avoid reimplementing when possible (as we all do).  It seems like it's creating more work than it's saving in this case.

**Comment by dmos62** [comment]
Ok, I thought about this a lot (and discussed it with @mathemancer) and I don't see a way to treat the `duplicates-only` filter as the rest of the filters. The problem is that it's fundamentally different. It groups the table on the specified columns and then filters the groups based on their size (sizes bigger than 1), thus filtering out unique rows (unique on specified columns), whereas the remaining filters (that are currently implemented/discussed) act on individual rows. Because of this, `duplicates-only` cannot compose the way the other filters can: `or(empty(col1), duplicates-only(col2))` has no sensible meaning.

We can implement `duplicates_only=[col1,col2]` as a separate `records` endpoint query parameter. But, we might as well drop it, because the underlying code would not generalize to `unique_only` and similar other group-attribute-based filters. By group-attribute I mean group size in this case, but it could be anything, for example a column sum of a group. If we wanted to implement `unique_only`, relevant code size would basically double.

I'm in favor of dropping current `duplicates_only` implementation completely. I think we need a fundamentally different approach. I have some idea of what that might be. I'll start a discussion for that.

**Comment by kgodey** [comment]
> Inorder to do this, the UX for filters needs to be rethought.

@pavish Could you explain in more detail why/how we need to rethink the UX if we make it a separate query parameter?

@dmos62 Can I assign this issue to you to come up with a spec? 

Please note that the requirement for this filter came from the [Working with Columns](https://wiki.mathesar.org/design/specs/working-with-columns) spec, specifically " User changes column settings to disallow duplicate values" (I recommend looking through the Figma prototype). The idea is that if a user tries to set a column to unique and it has non-unique values, we help them fix the error by filtering to rows with duplicates. (See the "Providing options to solve problems when presenting warnings (Help me fix this problem)" section of the spec). This is an important UX pattern for us - helping users identify and fix issues, we cannot remove the filter option entirely.

Let me know if you have any questions.

**Comment by dmos62** [comment]
> Can I assign this issue to you to come up with a spec?

@kgodey yes, I'll assign myself.

As pointed out earlier, with our current setup, we can't consider `duplicates_only` as a filter in the same sense that `empty`, `equal`, etc. are filters.

A quick fix (to enable the user to diagnose duplicate entries) is to move it to a separate query parameter and consider it a preprocessing step, something that happens before "regular" filtering. On the backend, current @mathemancer 's implementation should work out of the box. @pavish alluded that frontend would need more work.

The other option is to come up with the mechanics for generalizing such grouping-filtering operations (in other words coming up with a more powerful interface). We talked about this some last week with @mathemancer (#853). I get the sense that this would take some focused cooperation on the backend, for starters because it would affect multiple areas of code. On the design and frontend too, but the backend could expose a simplified interface until the other teams are ready to make those changes.

Which makes more sense at the moment? I'm leaning towards the quick fix, because I'm eager to get through the milestones faster; at the same time, doing the generalized mechanics for this is really exciting, it's just that it doesn't seem to be a low-hanging fruit.

**Comment by kgodey** [comment]
@dmos62 Let's go with the quick fix. I think we should hold off on the mechanics for generalizing until we have more use cases (see https://github.com/centerofci/mathesar/discussions/853#discussioncomment-1760411). I don't think we need it yet.

We can figure out what frontend changes are needed once @pavish is back.

**Comment by kgodey** [comment]
Thanks for the thorough explanation @pavish. I assigned this to myself to think more about it.

**Comment by mathemancer** [comment]
A quick note:  While I'm okay with the quick fix in the short-term, I think the idea of a user trying to make, e.g., a non-null, unique column out of a column that's missing values and has some duplicates is not too odd.  The query for that would be something like ```
SELECT * FROM mytable WHERE col1 IS NULL OR is_duplicate(col1);
```
I.e., this is a very simple idea "I want to make my email column an ID column, so I need to find rows that don't conform and fix them" that results in the need to combine the `duplicates_only` filter with the `is_null` filter using `or`, and I think the use case is valid (and not too edge).

As I think about it, we might get some traction by trying to reframe this problem away from the global processing that's necessary in the implementation to find duplicates (in this case, that can be swept under the 'implementation details' rug), and towards the conception the user would have "this row is returned because it shares values with others in the relevant column".  I.e., the `duplicates_only` filter should rather be a `is_duplicate` or `is_duplicated` or `is_nonunique` filter.  This makes the logic of how it should combine with other filters a bit clearer (for me, at least).

**Comment by dmos62** [comment]
> duplicates_only filter should rather be a is_duplicate or is_duplicated or is_nonunique filter

I had a similar train of thought. It's still somewhat complex. Because inside the filtering spec you'd be defining what groupings you need: for example, `is_duplicate(column="x")` needs a grouping on the uniqueness of column `x`; and, you'd have to perform the groupings before the specified filtering is applied. I'm still leaning towards doing all of this more explicitly as discussed in #853, since it's simpler and more expressive.

**Comment by mathemancer** [comment]
@dmos62 Thought:  With the new ranged grouping PR, you could in fact combine an arbitrary filter with `is_duplicate` by defining `is_duplicate` in terms of group size for a distinct grouping, and combining using our already-existing filtering logic.

**Comment by dmos62** [comment]
@mathemancer interesting. Is that because the group-attribute columns are dropped/unselected after the filtering is done? It might be a UX challenge to expose those columns as choices when creating an `is_duplicate` filter. Maybe a bit complicated from user's point of view? Seems a lot like what we discussed in #853, but with meta-columns always hidden.

**Comment by mathemancer** [comment]
I continued the conversation in the other thread you mentioned (#853 ).   Basically, the current set up is that all grouping metadata is "hidden" as a column from the user, and only exposed through the special UI elements for grouping.

**Comment by kgodey** [comment]
I'm going to close this issue since we've opened a new design issue to reevaluate the design. See #1028.
