### ISSUE TITLE
Slow response time from records API when in violation of a not-null constraint

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#858]
## Reproduce

1. Use the front end
1. Open a table where every column _can_ be NULL.
1. Click the `+` icon at the bottom left of the table to begin adding a new record.
1. Observe a request to `http://localhost:8000/api/v0/tables/24/records/` that completes in under 100 ms. Good.
1. Disallow NULL for one column.
1. Click the `+` icon again.
1. Observe that same request taking longer than 10 seconds to complete. Bad.

Related to #859

**Comment by pavish** [comment]
@seancolsen This only seems to take around ~1s in my local environment which is high but I assume it's because of the additional time taken by Django to print the debug error message.

I'm not sure what is causing 10s delay on your end. I'm marking this issue as draft until our backend team can take a look.

@centerofci/mathesar-maintainers

**Comment by mathemancer** [comment]
I took a quick look.  The problem is that the front end is sending a request to insert an empty row.  If there are `NOT NULL` columns without default values to insert, this causes an error.  I think we should
1. Avoid sending that request, _and_
2. handle that error more quickly on the back end.

**Comment by silentninja** [comment]
@seancolsen I am not able to reproduce the bug, please check this [video](https://www.loom.com/share/cf2f8b0b9d9945a3ba5ebd63fc751d56) and let me know if what I am doing is right.

**Comment by silentninja** [comment]
On the backend, the `null violation` error seems to be [captured](https://github.com/centerofci/mathesar/blob/f68e61b26d64d9c1d09cb779dbfebfb1479ea5bf/mathesar/api/viewsets/columns.py#L115) and converted into a `ApiException` which returns a text string and not the whole stack trace, so I am not sure if it is due to Django debug logs

**Comment by seancolsen** [comment]
@silentninja in your video you don't appear to ever have the table in a state where a NOT NULL constraint is set. When you're clicking on "Allow NULL" (to un-check the checkbox) that request is failing (as expected) because the table contains rows with NULL values. Here's a [video](https://www.loom.com/share/2998d8a109284b93852d468550c46b60) of me reproducing the slow response. See how long the row remains yellow. When it turns red that's when the front end finally receives the response from the server.

**Comment by silentninja** [comment]
I am able to reproduce the bug thanks!

**Comment by seancolsen** [comment]
@silentninja 

> I will create a new issue with regards to that

Cool thanks. I'll close this ticket then.
