### ISSUE TITLE
Multiple tables with the same oid

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#876]
## Description

Certain bugs or improper usage of django queryset reflection managers leads to the creation of multiple of Table objects for the same underlying table in the users table.

## To Reproduce
- Create a table directly on the user's database using `db.tables.operations.create.create_mathesar_table`, this won't create a Table object on mathesar's django database.
- Now create a Django Table object using `Table.objects.get_or_create(oid=db_table_oid, schema=schema)`
- There will be a race condition and two Table objects will be created
- Then Calling `models.Table.objects.get(oid=oid, schema=schema)` will throw the exception `mathesar.models.Table.MultipleObjectsReturned: get() returned more than one Table -- it returned 2!`

## Environment
Our docker container.

**Comment by mathemancer** [comment]
OIDs should be set to `unique=True` in the `DatabaseObject` model.  In fact, they should be globally unique on a per-DB basis.

**Comment by silentninja** [comment]
> OIDs should be set to `unique=True` in the `DatabaseObject` model. In fact, they should be globally unique on a per-DB basis.

Would definitely want this, we would still be getting an error but it should help us find the actual cause. Since the `oid` field is part of an abstract model, would want the unique to be in a meta object, so that it is easier to extend.

**Comment by Anish9901** [comment]
Can I work on this ?

**Comment by silentninja** [comment]
Thanks!, @Anish9901 I have assigned the issue to you.

**Comment by Anish9901** [comment]
Is there a way i can test this issue locally?

**Comment by Anish9901** [comment]
I have created a draft PR #1223 regarding this issue can someone please take a look.

**Comment by silentninja** [comment]
> Is there a way i can test this issue locally?

@Anish9901 I made changes to the issue description to easily reproduce the error

**Comment by Anish9901** [comment]
@silentninja I don't seem to be getting an exception. 
```
root@56faecbef872:/code# python manage.py shell
Python 3.9.10 (main, Mar  2 2022, 04:40:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from db.tables.operations.create import create_mathesar_table

In [2]: from mathesar.database.base import create_mathesar_engine

In [3]: from mathesar.models import *

In [4]: schema = Schema.objects.first()

In [5]: engine = schema.database.name

In [6]: engine = create_mathesar_engine(schema.database.name)

In [7]: engine
Out[7]: Engine(postgresql://mathesar:***@mathesar_db:5432/mathesar)

In [8]: schema
Out[8]: <Schema: Schema: 2200>

In [9]: create_mathesar_table("Test_table", schema.name, [], engine)
Out[9]: Table('Test_table', MetaData(bind=Engine(postgresql://mathesar:***@mathesar_db:5432/mathesar)), Column('id', Integer(), table=<Test_table>, primary_key=True, nullable=False), schema='public')

In [10]: from db.tables.operations.select import get_oid_from_table

In [11]: db_table_oid = get_oid_from_table(db_table.name, db_table.schema, engine)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-9c6bbb661ac7> in <module>
----> 1 db_table_oid = get_oid_from_table(db_table.name, db_table.schema, engine)

NameError: name 'db_table' is not defined

In [12]: db_table_oid = get_oid_from_table("Test_table", schema.name, engine)

In [13]: db_table_oid
Out[13]: 809252

In [14]: Table.objects.get_or_create(oid=db_table_oid, schema=schema)
Out[14]: (<Table: Table: 809252>, False)

In [15]: Table.objects.get(oid=oid, schema=schema)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-f15eba8e1304> in <module>
----> 1 Table.objects.get(oid=oid, schema=schema)

NameError: name 'oid' is not defined

In [16]: Table.objects.get(oid=db_table_oid, schema=schema)
Out[16]: <Table: Table: 809252>
```

**Comment by kgodey** [comment]
@Anish9901 Reproducing the bug depends on the race condition. `Table.objects.get_or_create(oid=db_table_oid, schema=schema)` needs to be run very quickly after `db.tables.operations.create.create_mathesar_table` is run. You may need to run it a few times to reproduce the race condition.

**Comment by silentninja** [comment]
@kgodey @Anish9901 I am not able to reproduce this issue, there are various checks that prevent a duplicate object from being created. For example:

https://github.com/centerofci/mathesar/blob/68a12dcb2961bf22dc123c7e344f9d66716738f1/mathesar/models.py#L180
https://github.com/centerofci/mathesar/blob/68a12dcb2961bf22dc123c7e344f9d66716738f1/mathesar/reflection.py#L63

I think `mathesar.models.Table.validate_unique` is not kicking incorrectly. Writing a deterministic test will be really hard for this issue, it would be better just to add a DB constraint as our goal is to prevent duplicate oid from getting into the database.

**Comment by kgodey** [comment]
@silentninja I think a DB constraint makes sense, it looks like https://github.com/centerofci/mathesar/issues/1218#issuecomment-1077770639 is already taking that approach.

**Comment by Anish9901** [comment]
@silentninja should I create a unique constraint in Database model on (oid, current_objects) or (oid, objects)? This would ensure uniqueness on db level right?

**Comment by silentninja** [comment]
@Anish9901 `current_objects` and `objects` are not columns of a table rather they are [queryset managers](https://docs.djangoproject.com/en/4.0/topics/db/managers/), it is not possible to add constraints to queryset managers. Currently, we have validation at the Django service layer and but it is not enforced on the database using database constraints. But the problem is that the service layer validation is being bypassed due to exceptions during program flow, so the only way to solve the issue is to use a database constraint.

**Comment by silentninja** [comment]
The reason why we are using a service layer validation currently is that it is not possible to establish a unique constraint across tables. So an alternate way should be considered to ensure integrity at the database level. @mathemancer Can you confirm this?

**Comment by mathemancer** [comment]
@silentninja This is correct. I suggest creating a proper model of `DatabaseObject` (or something descriptive) that has an `oid` and a database, a uniqueness constraint on the `oid` in that model, and referencing it from the `Schema`, `Table`, `View`, etc. models. We'd want to reflect the OID to that model, and then the other stuff to the specific model as appropriate. Deletion should happen from the `DatabaseObject` side, and cascade to the `Table` or whatever.

There are some other solutions, but I think this is the one that will play nicest with Django.

**Comment by Anish9901** [comment]
> @silentninja This is correct. I suggest creating a proper model of `DatabaseObject` (or something descriptive) that has an `oid` and a database, a uniqueness constraint on the `oid` in that model, and referencing it from the `Schema`, `Table`, `View`, etc.
@mathemancer Currently I have added a `database` column inside the `Table` model which is referencing from `Database` model and I am adding the unique constraint on the `oid` of Table and the `database` #1223. Is this ok or should I create another model inheriting `DatabaseObject` model which will have `database, schema and table` which are ForeignKey fields on their own models respectively and add a unique constraint on `(oid, database, schema and table)`?

**Comment by mathemancer** [comment]
> Currently I have added a `database` column inside the `Table` model which is referencing from `Database` model and I am adding the unique constraint on the `oid` of Table and the `database` #1223.

This solves part of the problem, but has some weaknesses.

First, the table is already associated with a database through its schema. This needs to be represented in the ORM modeling, lest these links get out of sync (what if the table is associated with a schema associated with database A, but the database attribute of the model points to database B?).

The broader problem is that `oid` is unique over a larger set of PostgreSQL database objects than those represented by one of our Django models. For example, there is a unique constraint on the union of Tables, Views, Indexes, and other 'selectable' objects in the database. See [the docs for `pg_class` for some details](https://www.postgresql.org/docs/13/catalog-pg-class.html). Also see [an explanation of OIDs in the Postgres wiki](https://wiki.postgresql.org/wiki/FAQ#What_is_an_OID.3F).

I was wrong before when I indicated that the OIDs were _guaranteed_ unique over the whole database. Instead, they're guaranteed unique over various subsets of objects, and the way to figure out those subsets appears to be to inspect the system tables. For most purposes, we can _treat_ the OIDs as unique over a database, but it's not actually true in all cases. The reason they can be treated that way is that they're generated globally by an integer sequence internally in PostgreSQL. Unfortunately, the type of the sequence is an unsigned 4-byte integer. This means that if there are more than 4 billion OID-identified objects in the database, the counter will rollover and there may be duplicates. This doesn't usually happen, but since the user is empowered to (for example) create a table that consumes OIDs for its primary key, it's possible.

@silentninja @kgodey Do you have any remaining strong opinions on whether we should really be enforcing this uniqueness in Django? The more I think about it, the more I like the idea of cleaning up after the fact by handling the error and adjusting the Django tables accordingly. If there's more than one table with the same OID, something is wrong beyond just violating the uniqueness constraint, and moreover I don't think we want to recreate the intricate dependencies between different PostgreSQL object types in Django, since it's already created and maintained in the PostgreSQL system tables.

Regardless, _if_ (big if) we want to enforce this in Django, it should probably still be over all database objects in a given database. I think that in the edge cases where that's not true, there'll be so many bugs in the users actual DB installation that whether we're reflecting things properly will be something of an afterthought.

**Comment by kgodey** [comment]
I don't think we should be enforcing `oid` uniqueness as as a database constraint, but I do think we can enforce it in _Django_ by overriding the `Table` model's `save` method to check if there's another object with the same `oid` before saving the `Table`. See [this Stack Overflow answer](https://stackoverflow.com/questions/54244869/how-to-enforce-database-constraints-between-two-foreign-keys-on-a-join-table). I think this is probably the cleanest option to prevent the error.

**Comment by mathemancer** [comment]
I guess using @kgodey's suggestion, we could also make "model sets" of objects where the uniqueness should be enforced over multiple models (e.g., `Table` and `View` models would be in the same set). Or were you thinking of just enforcing it model-by-model, and letting the DB tell us if there's a broader problem?

**Comment by silentninja** [comment]
> I don't think we should be enforcing `oid` uniqueness as as a database constraint, but I do think we can enforce it in _Django_ by overriding the `Table` model's `save` method to check if there's another object with the same `oid` before saving the `Table`. See [this Stack Overflow answer](https://stackoverflow.com/questions/54244869/how-to-enforce-database-constraints-between-two-foreign-keys-on-a-join-table). I think this is probably the cleanest option to prevent the error.

@kgodey We are already doing this by validating before saving the object https://github.com/centerofci/mathesar/blob/68a12dcb2961bf22dc123c7e344f9d66716738f1/mathesar/models.py#L180

The problem happens when there is an exception during reflection(not really sure) or incorrect use of reflection managers. Since it is a race condition issue, an easier option would be to have a unique database constraint over table oid and schema and use the service layer validation to check for uniqueness over the database which can be flexible 

Another option is to have the object reference an identifier using [generic foreign keys](https://docs.djangoproject.com/en/4.0/ref/contrib/contenttypes/#generic-relations-1) but we don't really need that much correctness as our primary concern is to prevent duplicate oid race condition and not about the correctness.

**Comment by mathemancer** [comment]
I could get onboard with a hybrid solution like what @silentninja is proposing

**Comment by Anish9901** [comment]
> The problem occurs due to incorrect use of reflection managers. Since it is a race condition issue, an easier option would be to have a unique database constraint over table oid and schema and use the service layer validation to check for uniqueness over the database.

@silentninja initially my PR https://github.com/centerofci/mathesar/pull/1223/ applied constraint over oid and schema but then I updated my PR based on @mathemancer's feedback. Now it looks like we have a consensus on going ahead with constraint on oid and schema. 

Here's my commit that makes the required changes: https://github.com/centerofci/mathesar/pull/1223/commits/99c771a975bf70357307c36ff87a9afbcc83255d. If this looks correct then I'll revert my PR to this commit and we'll merge this in.

**Comment by silentninja** [comment]
@Anish9901 https://github.com/centerofci/mathesar/commit/99c771a975bf70357307c36ff87a9afbcc83255d looks like the correct way forward. Please revert the PR to https://github.com/centerofci/mathesar/commit/99c771a975bf70357307c36ff87a9afbcc83255d also don't forget to run `makemigration` command after adding the constraint

**Comment by Anish9901** [comment]
>@Anish9901 https://github.com/centerofci/mathesar/commit/99c771a975bf70357307c36ff87a9afbcc83255d looks like the correct way forward. Please revert the PR to https://github.com/centerofci/mathesar/commit/99c771a975bf70357307c36ff87a9afbcc83255d also don't forget to run makemigration command after adding the constraint

@silentninja I have made these changes, this PR is ready for review.
