### ISSUE TITLE
Small bug in pagination component

### ISSUE THREAD

**Issue by mr-gabe49** [centerofci/mathesar#880]
## Description

When there are exactly 8 pages, the first page does not become active when supposed to. When the user clicks on the second page, they both become active. 

## Recommendation
- Changing  `<li class:active={page === pageInfo.start}>` to  `<li class:active={page === pageInfo.start - 1}>` in line 62 of `Pagination.svelte` file seems to fix the problem. 

## Additional context

![Screenshot (64)](https://user-images.githubusercontent.com/66047479/145625807-a63aaa8b-ba88-4caa-b323-64bd3839fb0f.png)

**Comment by seancolsen** [comment]
I'm observing this bug too. 

I'm also observing that changing `pageInfo.start` to `pageInfo.start - 1` seems fix it. But that seems weird to me. At the very least I think it's poor readability. At worst, I might consider it two bugs that cancel each other out.

Here's what I'd recommend:

- Modify `paginationUtils.ts` to fix the bug.
- Create a test for `calculatePages` with some basic assertions that pass.
- Add a test assertion that fails when there are 8 pages.
- Modify `calculatePages` to get all tests to pass.
- I might also consider improving some of the naming within PageInfo to be more descriptive.

**Comment by mr-gabe49** [comment]
@seancolsen @pavish I'm going to unassign myself for now because I'm still learning about writing tests. Just in case another contributor wants to take it right now.

**Comment by seancolsen** [comment]
Wanna lean? Here's a great opportunity.

## Tests in general

- Run all our tests with

    ```
    docker exec -it -w /code/mathesar_ui mathesar_service npm test
    ```
    
    If you should never see failures on the master branch.

- As you're developing, it can be helpful to re-run specific tests that you know to be failing (without running the whole suite, for time's sake). Do that with something like:

    ```
    docker exec -it -w /code/mathesar_ui mathesar_service npx jest TextInput
    ```

    In that example I used `TextInput`, which is a string within the name of a test file. Test files end with the extension `.test.ts` and can be located pretty much anywhere in the codebase. By convention, we place the test files alongside their implementation files. But some other projects choose to create a top-level directory for all their tests.

- We have some tests that target the functionality of Svelte components using [Testing Library](https://testing-library.com/docs/svelte-testing-library/intro/). _(Seriously, who named that project??)_

- It's actually even simpler to test [pure functions](https://en.wikipedia.org/wiki/Pure_function) though -- which is what we have in the case of this `calculatePages` function. We can do that with [Jest](https://jestjs.io/). We don't have any tests like this in our suite right now, though I'm adding one [here](https://github.com/centerofci/mathesar/pull/904/commits/5148e8404cb0c391fc68acffcfad14281ef01ce9) in an open PR.

- Overall we don't have that many tests for the front end. It would be great to add more! You can help!


## For the pagination component

1. Create a file `src/component-library/pagination/paginationUtils.test.ts` with the following content:

    ```ts
    import { calculatePages } from './paginationUtils';

    test('calculatePages', () => {
      expect(calculatePages(1, 1)).toEqual({
        pages: [1],
        start: 1,
        end: 1,
        prevPageWindow: 1,
        nextPageWindow: 1,
      });
    });
    ```

    Here I'm asserting that when I have only one page, and I'm on the first page, I should only see one page and yada yada.

1. Run that test with:

    ```
    docker exec -it -w /code/mathesar_ui mathesar_service npx jest paginationUtils
    ```

    You should see that it passes.

## Writing tests

- Functions like `test` and `expect` are automatically imported into scope by the test runner. Your editor should hopefully be smart enough to see that Jest is configured for our project and provide you some assistance in using those functions. You can find more in the [Jest docs](https://jestjs.io/docs/getting-started), but there's not much else you'll need if you follow the pattern above.
- After, `expect`, you'll use a [matcher](https://jestjs.io/docs/using-matchers). Above I've used `toEqual` which compare objects and arrays deeply. The simpler matcher is `toBe` which you can use for primitives like numbers, booleans, and strings -- but you can't use `toBe` on objects, which is what we have in this case.
- The `expect` call is an "assertion". We can put many of them within the same test, but the test will stop running when it hits the first failure.
- We can put many tests within the same file.
- Typically I'll have one test for each function, and many assertions within that test. You can also declare variables and do other logic within the test too if you're trying to build up complex scenarios with assertions throughout a workflow. As the scenarios get more complex, it can be helpful to create multiple tests for the same function, but I don't think we need to do that in this case.
- Deciding _what to test_, and _how_ can be an art! You generally want to try poking and the boundaries and edge cases. We don't have to go crazy with all sorts of assertions for every scenario. Just a few will do. We're not trying to test every possible input -- just some of the important ones. If you find a bug like this, it's great practice to write a test that fails before even beginning work on the fix.

## Next steps

- Write test assertions for:

    - `calculatePages(1, 7)`
    - `calculatePages(1, 9)`
    - `calculatePages(50, 100)`

    Those should all pass.

- Then write a test assertion for `calculatePages(1, 8)` which fails. Try to fix `calculatePages` to get that test to pass.

## Other notes

- I didn't write the `calculatePages` function. Just from looking at it, I have a hard time formulating an expectation of its return value. The difficultly in formulating an expectation is an indication that the readability of this code could be improved. Instead of `calculatePages(50, 100)`, I'd prefer to see something like `getPaginationInfo({ currentPage: 50, totalPages: 100 })` which returns a `PaginationInfo` object like:

    ```ts
    {
      totalPages: 100,
      currentPage: 50,
      currentWindow: [ 48, 49, 50, 51, 52 ],
      currentPageAfterAdvancingWindowBackward: 45,
      currentPageAfterAdvancingWindowForward: 55
    }
    ```

    You can work toward improving this readability if you like, but it's not necessary when fixing the bug.

- To play with the `calculatePages` function, I found it helpful to do

    1. `cd mathesar_ui`
    1. `deno repl`

        (See [Deno](https://deno.land/))

    1. `import { calculatePages } from './src/component-library/pagination/paginationUtils.ts';`

    1. `calculatePages(50, 100)`

**Comment by mr-gabe49** [comment]
@seancolsen Thank you so much for that info! I've been learning about jest and the testing library but its taking me sometime to get my ahead around what to test for. Not sure how long it will take me but I'll do it. :)

**Comment by pavish** [comment]
@seancolsen The comment on how to write tests is very well written. I think it would be useful to add it to our frontend README or as a wiki page. Would you mind copying it over to either of the places?
