### ISSUE TITLE
UX for Selecting and Editing Cells

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#917]
## Problem
We need to define the user experience for selecting and editing cells in tables. 

## Proposed solution
A set of guidelines for implementing cell selection and editing interactions for all types of data and selection controls (checkbox, dropdown) supported by Mathesar.
The design should also consider scenarios for multi-select, bulk editing, and other scenarios that involve multi-cell operations such as copying and pasting content.

## Additional context
- [PR for Handle NULL Values](https://github.com/centerofci/mathesar-wiki/pull/13)

**Comment by kgodey** [comment]
I was thinking more about the concerns about users being used to spreadsheet interactions brought up in https://github.com/centerofci/mathesar-wiki/pull/13. I do think those concerns make sense, but I'm also concerned about data integrity. I think a good solution might be to have two different editing modes:
– the default one can be focused on data integrity and require double clicks to edit a cell.
- we can also have a "spreadsheet mode" that users would enable for rapid data entry, we can then switch to spreadsheet interactions just like Excel, Google Sheets, etc. when "spreadsheet mode" is enabled, we can display a warning above the table or something like that so that the user knows to be extra careful.

**Comment by seancolsen** [comment]
@ghislaineguerin @kgodey can we close this ticket?

**Comment by ghislaineguerin** [comment]
@seancolsen closing is fine. I don't think this is relevant anymore.
