### ISSUE TITLE
Blur via keyboard after entering edit mode on a NULL cell should cancel edits

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#929]
## Reproduce

1. Double click a NULL cell to enter edit mode.
1. Press `Esc` or `Tab` or `Enter`.
1. Observe the mode changing from edit to select.
1. Expect cell value to remain NULL.
1. Observe cell value is set to an empty string.

The expected behavior is described in [NULL Value Specs, scenario 2d](https://wiki.mathesar.org/design/specs/specs-null-values#steps-for-2d).

**Comment by aviwad** [comment]
Hello! Could I get assigned to this? Sounds interesting. I think i can fix this.

Would you know which functions are run when a cell is selected / deselected? that would help me check why NULL value is overwritten with empty string.

**Comment by pavish** [comment]
Hi @aviwad, this behavior was modified in several PRs after this issue was raised, rendering this issue void. Sorry that we did not check and close this earlier.

As a followup, there are couple issues which were raised:
* https://github.com/centerofci/mathesar/issues/1134
   - This is already assigned and is being worked upon
* https://github.com/centerofci/mathesar/issues/1116
    - Would you be interested in working on this one?
