### ISSUE TITLE
DB Types in column.valid_target_types are not in sync with the types returned in database types endpoint

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#932]
## Description
* `valid_target_types` property of column returns "DOUBLE PRECISION"
   - Endpoint: /api/v0/tables/14/columns/
* Types endpoint returns mathesar types where Number has the db type "DOUBLE_PRECISION"
   - http://localhost:8000/api/v0/databases/1/types/
   - Mathesar type: Number

Note that "DOUBLE PRECISION" and "DOUBLE_PRECISION" differ from each other.

## Expected behavior
Both endpoints should return values with same spelling.

**Comment by dmos62** [comment]
This is an interesting one. Database types belong to multiple namespaces and they are clashing. More specifically, SQLAlchemy gives types what it calls a `__visit_name__`, which for the double precision is `DOUBLE_PRECISION`, but the rest of our code seems to expect that to be `double precision` (notice space instead of underscore; case doesn't seem to matter).

@mathemancer would you mind taking a look? I branched off master and pushed three commits: one for the trace (reload `http://localhost:8000/api/v0/databases/1/types/` to see it in your `docker-compose up` output); one for fixing a bug in the tests (`==` instead of `=`); and, one for testing setting a column's type to double precision (the test fails, because column's returned type includes an underscore.

https://github.com/centerofci/mathesar/commits/backend-type-name-spaces
