### ISSUE TITLE
Restructure our URLs into a hierarchy

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#974]
## Problem
Our API router:

```
router = routers.DefaultRouter()
router.register(r'tables', viewsets.TableViewSet, basename='table')
router.register(r'schemas', viewsets.SchemaViewSet, basename='schema')
router.register(r'databases', viewsets.DatabaseViewSet, basename='database')
router.register(r'data_files', viewsets.DataFileViewSet, basename='data-file')
```

We are treating tables, schemas and databases as being on the same hierarchical level. However, in terms of Postgres, there's [a non-flat hierarchy between these entities](https://www.postgresql.org/docs/9.1/ddl-schemas.html). In specific terms, if we are addressing a table in Postgres (or in Mathesar), it will necessarily belong to a schema, which will belong to a database. Our current URL scheme does not reflect this. I.e. the URL `/api/v0/tables/1` does not tell you what database and schema the table belongs to.

## Proposed solution
A URL scheme like `/api/v0/databases/1/schemas/1/tables/1`. And, possibly something similar for the frontend URLs (currently they're of the form `/mathesar_tables/1`).

We are already doing this for table sub-entities, like column or constraint:

```
table_router = routers.NestedSimpleRouter(router, r'tables', lookup='table')
table_router.register(r'records', viewsets.RecordViewSet, basename='table-record')
table_router.register(r'columns', viewsets.ColumnViewSet, basename='table-column')
table_router.register(r'constraints', viewsets.ConstraintViewSet, basename='table-constraint')
```

**Comment by silentninja** [comment]
I prefer to have it as flat as much as possible. My reasons are:

1. Django prefers to have a flat hierarchy and is structured around it. I would avoid fighting an opinionated framework as much as possible
2. Drf nested routers do not pass the related parent object automatically, so the advantages are pretty limited.
3. It is easier to store the `identifier` of an object and let the object know about its hierarchy than store the whole hierarchy. Most resources that are not nested now (`tables`) can work individually well compared to the nested resource(`columns`)

**Comment by kgodey** [comment]
The flattening of the URL structure was a deliberate choice, see point #4 in our [API standards' "URLs" section](https://wiki.mathesar.org/en/engineering/architecture/api-standards#urls). This follows general RESTful URL standards where resources are at the top level wherever possible (also see [White House API standards](https://github.com/WhiteHouse/api-standards#restful-urls) which inspired ours).

We only do sub-resources when the resources are a part of the parent resource. Editing records, columns, or constraints also makes changes to the table, so they are sub-resources. Editing a table does not edit a schema or a database. Feel free to add this to the wiki page.

---

Some general feedback on this issue:
- Your issue description does not describe _why_ this change should be made. Why should the URL `/api/v0/tables/1` tell you what database and schema the table belongs to? Who does it benefit? What are the drawbacks (e.g. longer URLs, harder to type, etc.) and why are they worth this change?
- Please propose changes that affect the frontend (e.g. API structure) and/or large parts of the codebase as a GitHub discussion for feedback before creating an issue.
   - Definitely do not mark issues like these as `status: ready`, since an outside contributor could start work on it assuming it was fully specced out.
   - I'd also recommend applying [Chesterton's Fence](https://wiki.lesswrong.com/wiki/Chesterton%27s_Fence) while suggesting changes – understand why things are the way they are before proposing reforms.
- Please ensure there's only one `status` label in an issue (this feedback is for @silentninja since he added the second label).

**Comment by dmos62** [comment]
Thanks for the feedback. I'll keep those things in mind.

I did notice that I didn't provide a why. I had a knee jerk reaction to our url scheme, but didn't examine it. If I think about it now, I expected the table index, for example, to uniquely identify the table within a database or a schema, but not within the database cluster. In other words, the universal resource locator didn't seem universal. I also wasn't aware of flat routes being popular, which is interesting to learn.

I'd add that suggesting a reform is a good way to learn why things are the way they are. I definitely learned something, haha.

**Comment by kgodey** [comment]
>  I expected the table index, for example, to uniquely identify the table within a database or a schema, but not within the database cluster. In other words, the universal resource locator didn't seem universal. 

Table IDs are indeed universal, they don't depend on the database or schema. The URL wouldn't work otherwise.

> I'd add that suggesting a reform is a good way to learn why things are the way they are. I definitely learned something, haha.

Suggesting reforms is totally fine, but perhaps you could instead structure it as a discussion along the lines of? "why are URLs structured this way? it makes more sense to me to structure them in this other way because of reasons X, Y, and Z." I'm wary of creating issues since people not familiar with the project might start working on them and that would lead to a poor contribution experience.

---

I assume this issue can be closed?

**Comment by dmos62** [comment]
@kgodey I think we're on the same page. I'm closing the issue.

**Comment by kgodey** [comment]
Thanks @dmos62!
